### ISSUE TITLE
I need a little help.

### ISSUE THREAD

**Issue by Dringar** [zmaster587/AdvancedRocketry#101]
My game keeps crashing as soon as I open a world. I only have Advanced rocketry, LibVulpes, and Buildcraft installed, and I also have a pretty decent computer. Any help?

**Comment by zmaster587** [comment]
Can you please post a crash report or the fml-latest.log?  It's impossible to know what's going on without a bit of information.

**Comment by Dringar** [comment]
[15:01:36] [main/INFO]: Setting user: Dringar
[15:01:38] [Client thread/INFO]: LWJGL Version: 2.9.1
[15:01:43] [Twitch authenticator/ERROR]: Given twitch access token is invalid
[15:01:53] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Advanced Rocketry, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BuildCraft Compat, FMLFileResourcePack:Vulpes library
[15:01:57] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
[15:01:57] [Client thread/INFO]: Created: 16x16 textures/items-atlas
[15:01:57] [Sound Library Loader/INFO]: Sound engine started
[15:01:58] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Advanced Rocketry, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BuildCraft Compat, FMLFileResourcePack:Vulpes library
[15:01:59] [Client thread/INFO]: Created: 512x512 textures/blocks-atlas
[15:02:00] [Client thread/INFO]: Created: 512x256 textures/items-atlas
[15:02:00] [Sound Library Loader/INFO]: Sound engine started
[15:02:09] [Client thread/INFO]: Deleting level rockets
[15:02:09] [Client thread/INFO]: Attempt 1...
[15:02:15] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[15:02:15] [Server thread/INFO]: Generating keypair
[15:02:15] [Server thread/INFO]: Preparing start region for level 0
[15:02:16] [Server thread/INFO]: Preparing spawn area: 4%
[15:02:17] [Server thread/INFO]: Preparing spawn area: 12%
[15:02:18] [Server thread/INFO]: Preparing spawn area: 23%
[15:02:19] [Server thread/INFO]: Preparing spawn area: 33%
[15:02:20] [Server thread/INFO]: Preparing spawn area: 47%
[15:02:21] [Server thread/INFO]: Preparing spawn area: 63%
[15:02:22] [Server thread/INFO]: Preparing spawn area: 79%
[15:02:23] [Server thread/INFO]: Preparing spawn area: 99%
[15:02:24] [Server thread/INFO]: Changing view distance to 24, from 10
[15:02:24] [Server thread/WARN]: Invalid statistic in C:\Users\User\AppData\Roaming\.minecraft\saves\New World\stats\7d7671f0-6030-42b3-92f3-edfe1b44acd1.json: Don't know what stat.timeSinceDeath is
[15:02:24] [Server thread/WARN]: Invalid statistic in C:\Users\User\AppData\Roaming\.minecraft\saves\New World\stats\7d7671f0-6030-42b3-92f3-edfe1b44acd1.json: Don't know what stat.useItem.minecraft.jukebox is
[15:02:24] [Server thread/INFO]: Dringar[local:E:c8daee2c] logged in with entity id 147 at (-193.5, 66.0, -114.5)
[15:02:24] [Server thread/INFO]: Dringar joined the game

**Comment by Dringar** [comment]
Then it crashes with the Shutting Down Internal Server screen.

**Comment by zmaster587** [comment]
Are there any files in the the crash-reports folder?  If so can you post the most recent, preferably on http://pastebin.com ?

**Comment by Dringar** [comment]
How do I know which crash is the right one?

**Comment by Dringar** [comment]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 3/20/16 3:21 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectIntBufferU.get(Unknown Source)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectIntBufferU.get(Unknown Source)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 189342120 bytes (180 MB) / 389709824 bytes (371 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	AdvancedRocketry{1} [Advanced Rocketry] (minecraft.jar) 
	UCHIJAAAA	libVulpes{0.0.6e} [Vulpes library] (LibVulpes-0.0.6e.jar) 
	UCHIJAAAA	advancedRocketry{0.4.12b6} [Advanced Rocketry] (AdvancedRocketry-0.4.12b6.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 210/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce 210/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by zmaster587** [comment]
Does this still occur with minimun view distance?

**Comment by Dringar** [comment]
lemme check.

**Comment by GreenCafe** [comment]
This crash often occurs with certain graphic settings too high when first loading. Try turning them down and going again, It should work. I've experienced the same issue before, with a near identical crash log.

**Comment by Dringar** [comment]
It works now, but i also had to allocate 4 gigs of ram and set the priority to high on task manager.

**Comment by Dringar** [comment]
Thanks guys (better than galacticraft)
