### ISSUE TITLE
XML Planet Loader Error

### ISSUE THREAD

**Issue by Arashiiku** [zmaster587/AdvancedRocketry#1086]
Minecraft Version:
1.7.10
Forge Version:
(newest one for 1.7.10)
Advanced Rocketry Version:
Current
LibVulpes Version:
Current
**is this the latest curseforge build?**
Yes
----------
Explain issue in detail:
I'm not a java dev so imma copy paste what my friend who built the custom pack sent me.

But the short and sweet of it is that he has tried to add some more planets with the biomes from other mods that arnt spawning in our overworld.

and after finishing as such it isnt working for some reason was wondering if we could get some help.

[21:27:17] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
java.lang.NullPointerException
at zmaster587.advancedRocketry.util.XMLPlanetLoader.readAllPlanets(XMLPlanetLoader.java:334) ~[XMLPlanetLoader.class:?]
at zmaster587.advancedRocketry.AdvancedRocketry.serverStarting(AdvancedRocketry.java:1691) ~[AdvancedRocketry.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[modpack.jar:?]
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]

**Comment by Arashiiku** [comment]
https://cdn.discordapp.com/attachments/318912915313000460/404841112818155520/planetDefs.xml

**Comment by dmodoomsirius** [comment]
can you be specific about your version of Advanced Rocketry and LibVulps? current does not tell us what version.

**Comment by zmaster587** [comment]
what build number are you running, I know you said latest curseforge, but in the latest curseforge build, the stack trace is pointing me to a line with no code on it

**Comment by Arashiiku** [comment]
Thanks for the responce, It's my friend's pack once i get his attention (he lives on the east coast while im in the UK so have to wait for him to get up)

**Comment by Arashiiku** [comment]
Minecraft Forge 10.13.4.1614.
AR- 1.0.19b
LibVulpes 0.1.19

**Comment by Arashiiku** [comment]
I'm no coder, once he redoes the XML to adjust for the spaces i'll give an update as to wether it's working.

**Comment by Arashiiku** [comment]
so the spaces didnt affect anything.

**Comment by zmaster587** [comment]
Those are both really old versions of the mod, that explain why the line numbers are not matching.  One thing I noticed with curse, it's not displaying the latest 1.7.10 version on the front page, you need to go under files to see it for some odd reason.  I'll see if I can figure out what's wrong with it for that build.

Right now curse is down for a migration so you'll not be able to pull the files.  If you do want to upgrade now you can also pull the latest build here  too http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/RoundPlanets7_10/
http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/unstable1_7/

I'll get back to you in a few minutes on what's up with the XML

**Comment by zmaster587** [comment]
I changed "numplanets" in "Icy", "Chilly", and "Hot" to "numPlanets" and it worked fine on my end after that.  Maybe give that a shot?

**Comment by Arashiiku** [comment]
thanks dude. once we test i'll let you know

**Comment by Arashiiku** [comment]
yep it worked... thanks dude you save us

**Comment by zmaster587** [comment]
No problem!
