### ISSUE TITLE
ClassCastException: WorldDummy cannot be cast to WorldServer

### ISSUE THREAD

**Issue by DarkGuardsman** [zmaster587/AdvancedRocketry#125]
Pretty sure this is an issue with morph, however just in case its on your side
```
java.lang.ClassCastException: zmaster587.advancedRocketry.world.util.WorldDummy cannot be cast to net.minecraft.world.WorldServer
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1589)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:272)
    at net.minecraft.entity.passive.EntityBat.func_70071_h_(SourceFile:109)
    at morph.client.core.TickHandlerClient.worldTick(TickHandlerClient.java:851)
```
http://pastebin.com/sPNB5sNs

**Comment by zmaster587** [comment]
I cannot see any possible way that entityBat could make a reference to WorldDummy, nor can I think of  a reason WorldServer should be loaded on the client.
