### ISSUE TITLE
Crash after building space station

### ISSUE THREAD

**Issue by ikkerens** [zmaster587/AdvancedRocketry#1312]
## Version of Advanced Rocketry
1.4.0-81
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.2.8-31
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/TtrqkYEH

## Description of the problem
I've been trying to create a Space Station, scanned it, completed, press build, and as soon as the build laser hits the floor, the server crashes and will enter a crash-loop (chunk is chunkloaded).
Have to remove the `minecraft:arstationbuilder` tile entity for the server to start back up again.

After doing so, I've tried to reproduce the issue and the server crashed again.
If you need any more info or files, feel free to ask, it's reliable reproducible.

**Comment by zmaster587** [comment]
It appears to be failing on a copying a tile entity, can you send what you have and check the log file for "A TileEntity [something] has thrown an exception during loading" and "skipping BlockEntity with id [something]"?

Additionally, can you take a screenshot of the station you are trying to build?

**Comment by ikkerens** [comment]
I seem to have been able to resolve it by removing after all EnderIO conduits, I did so because of this error as you described:
```
[10:03:41] [Server thread/ERROR] [FML]: A TileEntity enderio:tile_conduit_bundle(crazypants.enderio.conduits.conduit.TileConduitBundle) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException: null
	at crazypants.enderio.conduits.conduit.TileConduitBundle.onAfterNbtRead(TileConduitBundle.java:218) ~[TileConduitBundle.class:?]
	at crazypants.enderio.base.TileEntityEio.readCustomNBT(TileEntityEio.java:85) ~[TileEntityEio.class:?]
	at com.enderio.core.common.TileEntityBase.func_145839_a(TileEntityBase.java:98) ~[TileEntityBase.class:?]
	at zmaster587.libVulpes.util.ZUtils.createTile(ZUtils.java:116) [ZUtils.class:unspecified]
	at zmaster587.advancedRocketry.util.StorageChunk.copyWorldBB(StorageChunk.java:501) [StorageChunk.class:?]
	at zmaster587.advancedRocketry.util.StorageChunk.cutWorldBB(StorageChunk.java:604) [StorageChunk.class:?]
	at zmaster587.advancedRocketry.tile.TileStationBuilder.assembleRocket(TileStationBuilder.java:110) [TileStationBuilder.class:?]
	at zmaster587.advancedRocketry.tile.TileRocketBuilder.performFunction(TileRocketBuilder.java:196) [TileRocketBuilder.class:?]
	at zmaster587.libVulpes.tile.TileEntityRFConsumer.func_73660_a(TileEntityRFConsumer.java:123) [TileEntityRFConsumer.class:unspecified]
	at net.minecraft.world.World.func_72939_s(World.java:1832) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

This error preceded the error that caused the actual server crash that you can see in the crash report.

**Comment by tahg** [comment]
I've had this same issue on a server I run.  It doesn't seem to be caused by EnderIO in my case.  I was able to restart the server by enabling Remove Erroring TEs in Forge, but not yet sure if there are other problems.  I can investigate more if I know what to look for.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
