### ISSUE TITLE
Crash when clicking "Up" in Destination screen

### ISSUE THREAD

**Issue by roboderpy** [zmaster587/AdvancedRocketry#1346]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-85-universal
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-32-universal
## Version of Minecraft
1.12.2

## Traceback
```
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at zmaster587.libVulpes.inventory.modules.ModuleContainerPan.actionPerform(ModuleContainerPan.java:168)
    at zmaster587.libVulpes.inventory.GuiModular.actionPerformed(GuiModular.java:50)
    at zmaster587.libVulpes.inventory.modules.ModuleContainerPan.onMouseClicked(ModuleContainerPan.java:242)
    at zmaster587.advancedRocketry.inventory.modules.ModulePlanetSelector.onMouseClicked(ModulePlanetSelector.java:343)
    at zmaster587.libVulpes.inventory.GuiModular.mouseClicked(GuiModular.java:91)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1757)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1096)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3937)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at launcher.lOlkEKchebureK.LoLkeKChEbUREk(SourceFile:322)
    at launcher.lOlkEKchebureK.main(SourceFile:203)
```

## Description
![javaw_2018-07-03_08-52-02](https://user-images.githubusercontent.com/6339511/42194487-5eb15ce6-7e9e-11e8-9985-e46026be96a6.png)
![2018-07-03_08-52-28](https://user-images.githubusercontent.com/6339511/42194493-6b74591a-7e9e-11e8-8858-60c91e5a4516.png)

**Comment by zmaster587** [comment]
This should have been fixed in build 86, can you try 86 or newer?

**Comment by roboderpy** [comment]
Will try

**Comment by roboderpy** [comment]
seems working
