### ISSUE TITLE
Non-fatal Casting Error

### ISSUE THREAD

**Issue by KittenKoder** [zmaster587/AdvancedRocketry#1370]
## Version of Advanced Rocketry
1.4.0-93
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.2.8-36
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
`[11:21:33] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.minecraft.client.multiplayer.WorldClient cannot be cast to net.minecraft.world.WorldServer
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassCastException: net.minecraft.client.multiplayer.WorldClient cannot be cast to net.minecraft.world.WorldServer
	at zmaster587.libVulpes.network.PacketHandler.sendToPlayersTrackingEntity(PacketHandler.java:154) ~[PacketHandler.class:unspecified]
	at zmaster587.advancedRocketry.tile.TileRocketBuilder.onRocketLand(TileRocketBuilder.java:931) ~[TileRocketBuilder.class:unspecified]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1002_TileRocketBuilder_onRocketLand_RocketLandedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at zmaster587.advancedRocketry.entity.EntityRocket.useNetworkData(EntityRocket.java:1415) ~[EntityRocket.class:unspecified]
	at zmaster587.libVulpes.network.PacketEntity.execute(PacketEntity.java:102) ~[PacketEntity.class:unspecified]
	at zmaster587.libVulpes.network.PacketEntity.executeClient(PacketEntity.java:112) ~[PacketEntity.class:unspecified]
	at zmaster587.libVulpes.network.BasePacket$BasePacketHandlerClient$executor.run(BasePacket.java:155) ~[BasePacket$BasePacketHandlerClient$executor.class:unspecified]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more`

## Description of the problem
It shows up in the log but doesn't cause a crash. On single player game. You might already know about this but most players don't look at the logs unless there is a crash so I figured it should be reported just in case you missed it.

**Comment by zmaster587** [comment]
Thanks for the heads up. Though there's an isRemote check there and client world shouldn't be returning false at that location.  Does this occur with only AR and Libvulpes?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Animalover609** [comment]
I'm getting this same issue too on latest build of both LibVulpes and Advanced Rocketry as of today (June 17th, 2019).
