### ISSUE TITLE
BE CAUTIOUS OF THIS MOD Completely Corrupted World

### ISSUE THREAD

**Issue by system-operator** [zmaster587/AdvancedRocketry#1425]
Completely corrupted my world save all by itself. So pissed off right now I don't care to post how to reproduce. Latest versions of all things, Forge 2760.

Thanks. Back to GC it is.

[14:32:52] [Server thread/INFO] [STDERR]: [zmaster587.advancedRocketry.event.PlanetEventHandler:worldSaveEvent:544]: java.lang.Exception: Missing Stars
[14:32:52] [Server thread/INFO] [STDERR]: [zmaster587.advancedRocketry.event.PlanetEventHandler:worldSaveEvent:544]:  at zmaster587.advancedRocketry.dimension.DimensionManager.saveDimensions(DimensionManager.java:563)
[14:32:52] [Server thread/INFO] [STDERR]: [zmaster587.advancedRocketry.event.PlanetEventHandler:worldSaveEvent:544]:  at zmaster587.advancedRocketry.event.PlanetEventHandler.worldSaveEvent(PlanetEventHandler.java:541)
[14:32:52] [Server thread/INFO] [STDERR]: [zmaster587.advancedRocketry.event.PlanetEventHandler:worldSaveEvent:544]:  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1790_PlanetEventHandler_worldSaveEvent_Save.invoke(.dynamic)
[14:32:52] [Server thread/INFO] [STDERR]: [zmaster587.advancedRocketry.event.PlanetEventHandler:worldSaveEvent:544]:  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[14:32:52] [Server thread/INFO] [STDERR]: [zmaster587.advancedRocketry.event.PlanetEventHandler:worldSaveEvent:544]:  at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[14:32:52] [Server thread/INFO] [STDERR]: [zmaster587.advancedRocketry.event.PlanetEventHandler:worldSaveEvent:544]:  at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1008)
[14:32:52] [Server thread/INFO] [STDERR]: [zmaster587.advancedRocketry.event.PlanetEventHandler:worldSaveEvent:544]:  at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408)
[14:32:52] [Server thread/INFO] [STDERR]: [zmaster587.advancedRocketry.event.PlanetEventHandler:worldSaveEvent:544]:  at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:446)
[14:32:52] [Server thread/INFO] [STDERR]: [zmaster587.advancedRocketry.event.PlanetEventHandler:worldSaveEvent:544]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579)
[14:32:52] [Server thread/INFO] [STDERR]: [zmaster587.advancedRocketry.event.PlanetEventHandler:worldSaveEvent:544]:  at java.lang.Thread.run(Thread.java:748)

**Comment by zmasterbah** [comment]
I'm sorry you ran into issues with the mod, however the only files written are advanced rocketry's own files.  World saving is carried out by vanilla.

Two things.  If I cannot replicate the issue I cannot fix it, so by not even givin me a starting point, it's hard for me to prevent this from happening in the future.

Three thing, you did not give me the version you're using.  Over the last few weeks I've had added additional safeguards, including creating a backup of AR's files to disk in the event of a failure such as this one(locations will be printed in the log).

Thirdly, in an event like this, I'll need information such as other mods in use (conflicts can happen) and a complete startup phase log so I can check for other debug output that can lead to the failure.

As a final note, if you're interested, if you send me the corrupt world folder, I will do what I can to try to restore it for you.

**Comment by zmaster587** [comment]
I'm sorry you ran into issues with the mod, however the only files written are advanced rocketry's own files. World saving is carried out by vanilla.

Three things. If I cannot replicate the issue I cannot fix it, so by not even giving me a starting point, it's hard for me to prevent this from happening in the future.

Second thing, you did not give me the version you're using. Over the last few weeks I've had added additional safeguards, including creating a backup of AR's files to disk in the event of a failure such as this one(locations will be printed in the log). I cannot stress enough that I need to know if those were one of the builds you were using. I get a lot of "latest version of all things" only to find aftee hours of debugging that it was 'latest version of all things as of when I checked last year', so I really do need numbers. It's not to make things difficult, it's to help save hours of time.

Thirdly, in an event like this, I'll need information such as other mods in use (conflicts can happen) and a complete startup phase log so I can check for other debug output that can lead to the failure.

As a final note, if you're interested, if you send me the corrupt world folder, I will do what I can to try to restore it for you.

**Comment by system-operator** [comment]
I posted in anger, and that was my fault. I don't believe it to be an issue with your mod at all. I think it was one of the other sketchier Stellar+API or Stellar+Skies mods that caused the issue. 

I haven't had any issues with AR, other than needing to remove other mods to make room for ID's :)

I apologize for the issue, and will continue to test this mod pretty thoroughly as I love it. 

Thank you, and sorry. If I have any further issues, I will just send you a note.

**Comment by zmaster587** [comment]
I do know that a failure in the on server start phase of any kind will result in advanced rocketry not yet loading from XML then became advanced rocketry saves it's XML and the dat on world save and MC saves the world when the game crashes.

There is one mod I know of that can cause odd generation on planets when there are certain biomes.  I want to say it was OTG and ocean biomes.  Sometimes near water edges it makes these massive spikes.  Not quite sure why to be honest.

Other than that and sponge, I'm not sure of any other mods that have serious compatabilty issues.

As a follow-up, if you are running build 108 or newer.  Can you check to see if the backup files were properly created/printed in the log.  In all of my testing it has worked but sometimes simulated tests vs the real thing doffer and I do want to make sure it's working in your case too.

Stellar skies I don't know much about, but yeah, if you do run into any more issues, create an issue on github or post in the support channel on the AR discord(that'll be faster since I check it more often)

I'll see if I can replicate the issue with stellar api and skies after work tonight.
