### ISSUE TITLE
ArrayIndexOutOfBoundsException after upgrading from 0.5.2 to 0.6.4

### ISSUE THREAD

**Issue by mskurnik** [zmaster587/AdvancedRocketry#155]
I am not sure if this if the same as #144 but I just upgraded from 0.5.2 to 0.6.4 (libvulpes 0.0.6 to 0.0.7) and I am getting the following error.  Reverting back to 0.5.2 fixes the issue.
```
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 2
        at zmaster587.advancedRocketry.util.EmbeddedInventory.func_70301_a(EmbeddedInventory.java:57)
        at zmaster587.advancedRocketry.tile.multiblock.TilePlanetAnalyser.func_70301_a(TilePlanetAnalyser.java:558)
        at zmaster587.advancedRocketry.tile.multiblock.TilePlanetAnalyser.isRunning(TilePlanetAnalyser.java:350)
        at zmaster587.advancedRocketry.tile.multiblock.TileMultiPowerConsumer.func_145845_h(TileMultiPowerConsumer.java:102)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- Block entity being ticked --
Details:
        Name: ARplanetAnalyser // zmaster587.advancedRocketry.tile.multiblock.TilePlanetAnalyser
        Block type: ID #2430 (tile.planetanalyser // zmaster587.advancedRocketry.block.multiblock.BlockMultiblockMachine)
        Block data value: 10 / 0xA / 0b1010
        Block location: World: (585,59,-5368), Chunk: (at 9,3,8 in 36,-336; contains blocks 576,0,-5376 to 591,255,-5361), Region: (1,-11; contains chunks 32,-352 to 63,-321, blocks 512,0,-5632 to 1023,255,-5121)
        Actual block type: ID #2430 (tile.planetanalyser // zmaster587.advancedRocketry.block.multiblock.BlockMultiblockMachine)
        Actual block data value: 10 / 0xA / 0b1010
```

**Comment by zmaster587** [comment]
There is a slight incompatibility between the planet analyser structure from 0.5.x to 0.6.x due to mechanics changes.  However destroying the planet analysers and rebuilding them should fix the issue.
