### ISSUE TITLE
How to fuel a rocket with the Advanced Rocketry mod

### ISSUE THREAD

**Issue by Cmdb26** [zmaster587/AdvancedRocketry#1612]
## Version of Advanced Rocketry
1.7.10-1.0.19b.jar
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
1.7.10
## Version of Minecraft
1.7.10
## Crash report or log (if applicable)
This never crashed.

## Description of the problem
I need help fueling my fuel tanks. I have been trying to for 1 hour and 27 minutes! Also, how do I build a Chemical Reactor multiblock? Any help I would accept!:) Thanks!
![2019-06-27_11 49 41](https://user-images.githubusercontent.com/52044694/60288633-df182880-98d1-11e9-832a-f641d25fe057.png)
![2019-06-27_11 49 46](https://user-images.githubusercontent.com/52044694/60288643-e5a6a000-98d1-11e9-9509-9b39601d395e.png)
![2019-06-27_11 49 54](https://user-images.githubusercontent.com/52044694/60288648-e8a19080-98d1-11e9-9e38-263e9dba67ea.png)

**Comment by MrEyeballs29** [comment]
Ok why are using 1.7 not 1.12. Everyone uses that version.

**Comment by Cmdb26** [comment]
Because 1.12 doesn't work for me.

**Comment by MrEyeballs29** [comment]
Why

**Comment by Cmdb26** [comment]
Don't know. I'm not go at code. However, I do know it's something to do with a mob container. I can show you the crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.3.0-1.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 6/26/19 10:48 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: zmaster587.advancedRocketry.asm.ModContainer
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:373)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:531)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:220)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: zmaster587.advancedRocketry.asm.ModContainer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:368)
	... 11 more
Caused by: java.io.FileNotFoundException: C:\Users\Caden\Desktop\1.10.2 Space (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:145)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 425021656 bytes (405 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 3 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
		FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
		Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.3.0-1.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4973' Renderer: 'Intel(R) UHD Graphics 620'

**Comment by Cmdb26** [comment]
1.12 crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-63.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 6/26/19 10:55 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: zmaster587.advancedRocketry.asm.ModContainer
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:382)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: zmaster587.advancedRocketry.asm.ModContainer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:377)
	... 11 more
Caused by: java.io.FileNotFoundException: C:\Users\Caden\Desktop\1.10.2 Space (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:145)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 582734856 bytes (555 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 4 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	|       | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	|       | mcp       | 9.42         | minecraft.jar                 | None                                     |
	|       | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | forge     | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-63.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4973' Renderer: 'Intel(R) UHD Graphics 620'

**Comment by Cmdb26** [comment]
Besides, I'm asking how to fuel my rocket.

**Comment by MrEyeballs29** [comment]
Use a bucket of fuel and scan the rocket.

**Comment by Cmdb26** [comment]
Thanks but what do you mean by "Use a bucket of fuel" as in right click on the fuel tank or use a fueling station?

**Comment by MrEyeballs29** [comment]
Just use in the tank.

**Comment by Cmdb26** [comment]
Thanks again but I tried that. Tanks don't have interfaces like a crafting table.

**Comment by Cmdb26** [comment]
Wait! Do you mean Pressurized Tanks or Liquid Fuel Tanks?

**Comment by MrEyeballs29** [comment]
In the fuel tanks

**Comment by Cmdb26** [comment]
Thanks Again. But there are two fuel tanks. Which one do you mean by "fuel tanks"?

**Comment by MrEyeballs29** [comment]
Fuel Tank Block

**Comment by Poxorosa** [comment]
> Thanks Again. But there are two fuel tanks. Which one do you mean by "fuel tanks"?

Try update java and give your mod list. 
Oh, and dont forget to install libvulpes.

**Comment by Gamertech** [comment]
Pump fuel into the fueling block, and use the LibVulpes linking tool to link the fueling block and the rocket controller.

**Comment by Silfryi** [comment]
@Cmdb26 Your rocket has not been built yet. Add more fuel tanks until, when you build the rocket, the builder says "cleared for liftoff". If it says "Not enough thrust", put more engines on. Repeat until it works.

**Comment by Cmdb26** [comment]
> Pump fuel into the fueling block, and use the LibVulpes linking tool to link the fueling block and the rocket controller.

Thanks so much! Now I can go to space! 
![2019-07-02_10 04 43](https://user-images.githubusercontent.com/52044694/60528112-f760bc80-9cb0-11e9-847c-db1cb8d0f4e2.png)

**Comment by Cmdb26** [comment]
I have a new issue though.:( [https://github.com/zmaster587/AdvancedRocketry/issues/1619](url)

**Comment by Cmdb26** [comment]
But I have a new issue!:( [https://github.com/zmaster587/AdvancedRocketry/issues/1619](url)

**Comment by Cmdb26** [comment]
But I have a new issue!:( (I can't put a link here), https://github.com/zmaster587/AdvancedRocketry/issues/1619

**Comment by MrEyeballs29** [comment]
That link is broken

**Comment by MrEyeballs29** [comment]
Good, a fixed link this time.

**Comment by dmodoomsirius** [comment]
Next time please don’t link issues within issues.

**Comment by CiangCing14** [comment]
> Pump fuel into the fueling block, and use the LibVulpes linking tool to link the fueling block and the rocket controller.

> > Pump fuel into the fueling block, and use the LibVulpes linking tool to link the fueling block and the rocket controller.
> 
> Thanks so much! Now I can go to space! ![2019-07-02_10 04 43](https://user-images.githubusercontent.com/52044694/60528112-f760bc80-9cb0-11e9-847c-db1cb8d0f4e2.png)

Please tell me how to pump? use the Fluid Pipe? I failed.

https://github.com/Nomi-CEu/Nomi-CEu/issues/1336
