### ISSUE TITLE
[BUG] Exception on load + crash with Dynamic Surroundings

### ISSUE THREAD

**Issue by Gamertech** [zmaster587/AdvancedRocketry#1729]
## Version of Advanced Rocketry
1.12.2-1.6.0-187

## Have you verified this is an issue in the latest unstable build
Y

## Version of LibVulpes
1.12.2-0.4.2-68

## Version of Minecraft
1.12.2
forge-14.23.5.2847

## Does this occur without other mods installed
Y

>If Y, what is the MINIMUM set of mods required.
Advanced Rocketry + LibVulpes

## Crash report or log or visualVM (if applicable)
Latest: https://pastebin.com/HW2YwE3r
Crash with DS: https://pastebin.com/HBB0vxVm

## Description of the problem
Install AR and LV, load the pack, check the logs for an exception.

To replicate the crash, add Dynamic Surroundings and create a version mismatch with another mod. In my case, the latest FTB Utilities relies on an FTBLib file that was named incorrectly.

During boot, Forge stalls at the missing dependancy screen, AR calls audio during boot from an OreLib process that hasn't loaded yet and triggers a CTD.

If there's no version mismatch or something to stall pack load, then the pack continues to load perfectly, but still generating the exception in the logs.

I've gone as far back as AR 1.12.2-1.6.0-164 and LV 1.12.2-0.4.1-60 still showing the same exception with no other mods installed.

**Comment by Gamertech** [comment]
Exception is still present with AR 1.6.0-190

**Comment by Gamertech** [comment]
This is the exception AR creates as the logs I posted have timed out:

`[14:24:53] [main/ERROR]: A critical problem occurred registering the ASM transformer class 
java.lang.ClassNotFoundException: 
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:46) [forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more`

As above, this exception is thrown with only AR/LV installed, and isn't with AR disabled.

**Comment by zmaster587** [comment]
The exception being printed is a known issue, but isn't related to anything that actually will impact the game at so it's been low priority.

As for the crash during the mismatch, ill investigate that.
