### ISSUE TITLE
[BUG] Microwave reciever makes client unplayable, completely obstructed vision.

### ISSUE THREAD

**Issue by Aririi** [zmaster587/AdvancedRocketry#1868]
## Version of Advanced Rocketry
>1.7.0-221

## Have you verified this is an issue in the latest unstable build
- No

## Version of LibVulpes
>0.4.2-75

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Unknown, unable to test.

## Crash report or log or visualVM (if applicable)
>Full logs available here: (No relevant information apparent)
https://lcars5201.ddns.net/index.php/s/TDy6ydPCiYQB8ea (1st relaunch)
https://lcars5201.ddns.net/index.php/s/bettwbQHsEQCdNd (2nd relaunch and troubleshoot att.)

## Description of the problem
>Build two microwave receivers, 1 satellite already in orbit.
>Place corresponding ID chip in input hatch, but standing on corner.
>Catch on fire but survive because that's why you made armor and can afford being stupid.
>While being on fire, the screen blinks in the shade of the skybox dep. on time of day, GUI disappears as well.
>At certain angles in certain positions, you can see everything normally, very, very small windows to allow this.
>Relaunch game, issue is still present, then /kill, screen goes blank entirely (shade is now static and unchanging) and cannot see GUI to respawn, relaunch again, no luck, so kick self from server only for main menu to be blocked by the same shade of the skybox. (Buttons not pressable.)

## Why is this important?
>Renders client unplayable.

**Comment by Aririi** [comment]
Latest snippet of logs upon joining, where the GUI and world is visible for a split-second:

`[21:46:17] [Client thread/INFO] [foamfix]: JEI search tree manager injection complete!
[21:46:19] [Client thread/INFO] [FML]: Applying holder lookups
[21:46:19] [Client thread/INFO] [FML]: Holder lookups applied
[21:46:20] [Netty Client IO #1/INFO] [FML]: [Netty Client IO #1] Client side modded connection established
[21:46:20] [Netty Client IO #1/INFO] [universalremote]: <UniversalRemote> Injecting vanilla packet interceptors...
[21:46:20] [Netty Client IO #1/INFO] [mcjtylib_ng]: DimensionSyncPacket: Registering: 
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded workbench model
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded importer model
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded exporter model
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded single_cable1 model
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded single_cable4 model
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded single_cable16 model
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded single_output1 model
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded single_output4 model
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded single_output16 model
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded single_input1 model
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded single_input4 model
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:66]: Loaded single_input16 model
[21:46:20] [Client thread/INFO] [mcjtylib_ng]: Received dimension information from server
[21:46:20] [Client thread/INFO] [EnderCore ASM]: Transforming Class [net.minecraft.world.chunk.storage.ExtendedBlockStorage], Method [func_76663_a]
[21:46:20] [Client thread/INFO] [EnderCore ASM]: Transforming net.minecraft.world.chunk.storage.ExtendedBlockStorage Finished.
[21:46:20] [Client thread/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.renderer.chunk.ChunkRenderDispatcher ...
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.bibliocraftmod.com/vcheck/version.txt
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.net.URL.openStream(Unknown Source)
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at jds.bibliocraft.VersionCheck.getNetVersion(VersionCheck.java:58)
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at jds.bibliocraft.VersionCheck$1.run(VersionCheck.java:46)
[21:46:26] [Thread-38/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.lang.Thread.run(Unknown Source)
[21:46:27] [Netty Client IO #1/INFO] [tconstruct-Config]: Syncing Config with Server
[21:46:29] [Client thread/INFO] [Quark ASM]: Transforming net.minecraft.client.gui.inventory.GuiBeacon$PowerButton
[21:46:29] [Client thread/INFO] [Quark ASM]: Could not locate, injecting method (Names [drawButton, func_191745_a] Descriptor (Lnet/minecraft/client/Minecraft;IIF)V)
[21:46:29] [Client thread/INFO] [Quark ASM]: Patch result: true
[21:46:29] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:111]: Spliced in METHOD: net.minecraft.world.chunk.BlockStateContainer.func_186018_a
[21:46:30] [Client thread/INFO] [buildinggadgets]: Received SyncedConfig from Server.
[21:46:30] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at p455w0rd.danknull.network.PacketConfigSync$Handler.handle(PacketConfigSync.java:79) ~[PacketConfigSync$Handler.class:?]
	at p455w0rd.danknull.network.PacketConfigSync$Handler.lambda$onMessage$0(PacketConfigSync.java:69) ~[PacketConfigSync$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 17 more
[21:46:30] [Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] Hello and welcome to StariCraft!\nNotice: Chat commands (ex: /home, /back) are not allowed during PvP or any sort of player-to-player interaction.
[21:46:30] [Client thread/INFO] [STDOUT]: [pl.asie.stackup.StackUpTransformer:patchMaxLimit:277]: Patched max stack check in lain/mods/cos/api/inventory/CAStacksBase -> getSlotLimit!
[21:46:30] [Client thread/INFO] [mcjtylib_ng]: Received dimlet rules from server
[21:46:30] [Client thread/INFO] [Actually Additions]: Created temporary WorldData to cache data on the client!
[21:46:30] [Client thread/INFO] [Actually Additions]: Receiving (new or changed) Player Data for player AririChan.
[21:46:31] [Client thread/INFO] [minecraft/AdvancementList]: Loaded 763 advancements
[21:46:31] [Client thread/INFO] [jei]: Ingredients are being added at runtime: 11 net.minecraft.item.ItemStack
Exception in thread "Thread-9" Jun 29, 2020 9:46:31 PM io.netty.util.ResourceLeakDetector reportUntracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.
[21:46:32] [Thread-39/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace ...
`

**Comment by Aririi** [comment]
After further investigation, it seems to be graphical issue with placing a chip inside a microwave receiver (that has a launches satellite.) Even at nighttime with a freshly installed client, the error occurred.

**Comment by Somdudewillson** [comment]
I have encountered the same issue.
