### ISSUE TITLE
[BUG]AdvancedRocketry can not use spacestation chip in server

### ISSUE THREAD

**Issue by JackMeds** [zmaster587/AdvancedRocketry#1876]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-229-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y
In FTB-Interactions modpack 

## Crash report or log or visualVM (if applicable)

When I press shift and right-click with spacestation chip, it will report an error in server console, and it will not open the GUI
https://paste.ubuntu.com/p/B8zNBYMBqv/
![image](https://user-images.githubusercontent.com/38741783/87392074-74ba4f00-c5de-11ea-8346-a7cdc14af5ae.png)

## Description of the problem
When I press shift and right-click with spacestation chip, it will report an error in server console, and it will not open the GUI

**Comment by yatounoneko** [comment]
Not only that, as long as the server seems to be unable to establish the space station

Whether by launching rockets (independent satellite silos) or manned rockets with navigation computers and satellite silos.

The rocket goes up into space and lands, but it goes straight out of space and back to earth. The platform of the original space station has not been generated. The single person mode is no problem.

It seems that the following errors will occur, but sometimes they will not be reported.
```

[13:30:05] [Server thread/ERROR] [minecraft/EntityTracker]: "Silently" catching entity tracking error.
>net.minecraft.util.ReportedException: Adding entity to track
at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:256) ~[ol.class:?]
at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:145) ~[ol.class:?]
at net.minecraft.world.ServerWorldEventHandler.func_72703_a(ServerWorldEventHandler.java:37) ~[op.class:?]
at net.minecraft.world.World.func_72923_a(World.java:1222) ~[amu.class:?]
at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1112) ~[oo.class:?]
at net.minecraft.world.WorldServer.impl$forceSpawnEntity(WorldServer.java:4889) ~[oo.class:?]
at net.minecraft.world.WorldServer.bridge$forceSpawnEntity(WorldServer.java:4869) ~[oo.class:?]
at org.spongepowered.common.entity.EntityUtil.processEntitySpawn(EntityUtil.java:744) ~[EntityUtil.class:1.12.2-2838-7.1.8]
at org.spongepowered.common.event.tracking.phase.packet.PacketState.processEntities(PacketState.java:78) ~[PacketState.class:1.12.2-2838-7.1.8]
at org.spongepowered.common.event.tracking.phase.packet.PacketState.processSpawnedEntities(PacketState.java:73) ~[PacketState.class:1.12.2-2838-7.1.8]
at org.spongepowered.common.event.tracking.phase.packet.player.InteractionPacketState.lambda$unwind$2(InteractionPacketState.java:210) ~[InteractionPacketState.class:1.12.2-2838-7.1.8]
at org.spongepowered.common.event.tracking.context.CapturedSupplier.acceptAndClearIfNotEmpty(CapturedSupplier.java:72) [CapturedSupplier.class:1.12.2-2838-7.1.8]
at org.spongepowered.common.event.tracking.phase.packet.player.InteractionPacketState.unwind(InteractionPacketState.java:201) [InteractionPacketState.class:1.12.2-2838-7.1.8]
at org.spongepowered.common.event.tracking.phase.packet.player.InteractionPacketState.unwind(InteractionPacketState.java:72) [InteractionPacketState.class:1.12.2-2838-7.1.8]
at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:316) [spongeforge-1.12.2-2838-7.1.8.jar:1.12.2-2838-7.1.8]
at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:618) [PhaseContext.class:1.12.2-2838-7.1.8]
at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:220) [PacketPhaseUtil.class:1.12.2-2838-7.1.8]
at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zla000(SourceFile:540) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.8]
at net.minecraft.server.MinecraftServer.redirect$onRun$zje000(MinecraftServer.java:4716) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
>Caused by: java.lang.IllegalStateException: Entity EntityItem['item.item.stationChip'/15741, l='world', x=-328.34, y=228.41, z=226.59] is already tracked for world: world
at net.minecraft.entity.EntityTracker.redirect$impl$reportEntityAlreadyTrackedWithWorld$zeg000(EntityTracker.java:1063) ~[ol.class:?]
at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:224) ~[ol.class:?]
... 28 more
```

**Comment by zmaster587** [comment]
@JackMeds Can you check to see if it occurs without other mods installed?

@yatounoneko Sponge is known to cause problems and isn't supported due to the high amount of effort, does your issue occur without sponge installed?
