### ISSUE TITLE
Ceating new worlds get stuck at 100% loading and using premade worlds crashes game immediately

### ISSUE THREAD

**Issue by Csquaredaap** [zmaster587/AdvancedRocketry#2010]
## Version of Advanced Rocketry
1.16

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.16

## Version of Minecraft
1.16

## Crash report and log, or VisualVM snapshot (if applicable)
>http://pastebin.com is a good place to put them
>crash reports that are put in the issue itself are impossible to read

> If it's an issue involving lag, please submit a VisualVM sampler snapshot.  Mods like lag goggles cannot provide all of the information needed to debug lag in any useful capacity.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

## Description of the problem

Yah when I try to make a new world the world never loads and when I use a world i alrdy made it crashes when I get anything from the creative menu that is related to the mod, but the problem is that the crash error is 0 so i get no text saying what happened

**Comment by Csquaredaap** [comment]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 3/20/21 5:21 PM
Description: Rendering screen

java.lang.RuntimeException: Provider zmaster587.advancedRocketry.capability.TankCapabilityItemStack.getCapability() returned null; return LazyOptional.empty() instead!
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:107) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:118) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at blusunrize.immersiveengineering.client.ClientEventHandler.onItemTooltip(ClientEventHandler.java:209) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_784_ClientEventHandler_onItemTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2609/278637334.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:271) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:702) ~[?:?] {re:mixin,re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:mixin:APP:wardance.mixins.json:MixinSweepDurabilitySuppressor,pl:mixin:A}
	at net.minecraft.client.gui.screen.Screen.func_231151_a_(Screen.java:123) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_230457_a_(Screen.java:118) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230457_a_(CreativeScreen.java:678) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:creative_inventory_slot,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230459_a_(ContainerScreen.java:164) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230430_a_(CreativeScreen.java:640) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:creative_inventory_slot,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:296) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:723) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:821) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:mvw.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.46.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$456/173115411.call(Unknown Source) [forge-1.16.5-36.0.46.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:107) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:118) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at blusunrize.immersiveengineering.client.ClientEventHandler.onItemTooltip(ClientEventHandler.java:209) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_784_ClientEventHandler_onItemTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2609/278637334.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:271) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:702) ~[?:?] {re:mixin,re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:mixin:APP:wardance.mixins.json:MixinSweepDurabilitySuppressor,pl:mixin:A}
	at net.minecraft.client.gui.screen.Screen.func_231151_a_(Screen.java:123) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_230457_a_(Screen.java:118) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230457_a_(CreativeScreen.java:678) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:creative_inventory_slot,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230459_a_(ContainerScreen.java:164) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230430_a_(CreativeScreen.java:640) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:creative_inventory_slot,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:296) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:723) ~[?:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.CreativeScreen
	Mouse location: Scaled: (232, 148). Absolute: (464.000000, 297.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Csquaredaap'/228, l='ClientLevel', x=-203.57, y=88.01, z=-155.05]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (-208,63,-158), Chunk: (at 0,3,2 in -13,-10; contains blocks -208,0,-160 to -193,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 586 game time, 586 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.46.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$456/173115411.call(Unknown Source) [forge-1.16.5-36.0.46.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2828395352 bytes (2697 MB) / 5435817984 bytes (5184 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.46.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.46.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.46.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.46.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.46.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.46
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |DONE      |NOSIGNATURE
		mining-helmet-1.16.4-2.0.0.jar                    |Mining Helmet                 |mining_helmet                 |2.0.0               |DONE      |NOSIGNATURE
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |DONE      |NOSIGNATURE
		kingvillager-1.6.1.jar                            |The King of the villagers     |kingvillager                  |1.6.1               |DONE      |NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.0.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.0      |DONE      |NOSIGNATURE
		looot-1.16.4-1.0.0.3.jar                          |Looot                         |looot                         |1.0.0.3             |DONE      |NOSIGNATURE
		colytra-forge-1.16.4-5.1.0.0.jar                  |Colytra                       |colytra                       |1.16.4-5.1.0.0      |DONE      |NOSIGNATURE
		Guide-API-VP-1.16.4-2.2.1.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.1               |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.0.jar                |Traveler's Backpack           |travelersbackpack             |5.4.0               |DONE      |NOSIGNATURE
		PlayerMobs-1.0.5.7.jar                            |Player Mobs                   |player_mobs                   |1.0.5.7             |DONE      |15:a4:a3:0e:d2:f8:64:0c:a4:97:30:5f:48:ba:5f:69:f9:23:42:14:a8:5a:60:3a:b1:b1:29:1a:0a:37:3c:79
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		Guard-Villagers-Mod-1.16.4.jar                    |Guard Villagers               |guardvillagers                |1.1.8               |DONE      |NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		PiratesAndLootersMod7.0-1.16.4.jar                |Pirates_And_Looters_Mod       |pirates_and_looters_mod       |1.0.0               |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.46-universal.jar                |Forge                         |forge                         |36.0.46             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		scuba-gear-1.16.5-1.0.2.jar                       |Scuba Gear                    |scuba_gear                    |1.0.2               |DONE      |NOSIGNATURE
		structure_gel-1.16.4-1.7.5.jar                    |Structure Gel API             |structure_gel                 |1.7.5               |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.46-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		customizableelytra-1.16.4-1.3.0.jar               |Customizable Elytra           |customizableelytra            |1.3.0               |DONE      |NOSIGNATURE
		mana-and-artifice-1.3.0.2.jar                     |Mana and Artifice             |mana-and-artifice             |1.3.0.2             |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.5-4.2.4-134.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-4.2.4-134    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		MekanismAdditions-1.16.5-10.0.21.448.jar          |Mekanism: Additions           |mekanismadditions             |10.0.21             |DONE      |NOSIGNATURE
		Numina-1.16.4-2.0.4.jar                           |Numina                        |numina                        |2.0.4               |DONE      |NOSIGNATURE
		ModularPowersuits-1.16.4-2.0.2.jar                |MachineMuse's Modular Powersui|powersuits                    |1.0.0               |DONE      |NOSIGNATURE
		AdvancedRocketry-1.16.5-1.7.1-1-universal.jar     |Advanced Rocketry             |advancedrocketry              |1.16.5-1.7.1-1      |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.71.jar                           |Just Enough Items             |jei                           |7.6.1.71            |DONE      |NOSIGNATURE
		wardance-0.3.3.jar                                |Project: War Dance            |wardance                      |0.3.3               |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.0      |DONE      |NOSIGNATURE
		Artifacts-1.16.5-2.8.3.jar                        |Artifacts                     |artifacts                     |1.16.5-2.8.3        |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		backpacked-1.7.0-1.16.3.jar                       |Backpacked                    |backpacked                    |1.7.0               |DONE      |NOSIGNATURE
		backpacker-1.2.2-1.16.3.jar                       |Backpacker                    |backpacker                    |1.2.2               |DONE      |NOSIGNATURE
		illagersweararmor-1.0.3.jar                       |Illagers Wear Armor           |illagersweararmor             |1.0.3               |DONE      |NOSIGNATURE
		obfuscate-0.6.0-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.0               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		Desolation+1.0.5b+1.16.5.jar                      |Desolation (Forge)            |desolation                    |1.0.5b              |DONE      |NOSIGNATURE
		guncus-1.16.4-2.0.jar                             |Gun Customization: Infinity   |guncus                        |1.16.4-2.0          |DONE      |NOSIGNATURE
		Undercover+Witches+1.0.1.jar                      |Undercover Witches            |undercoverwitches             |1.0.1               |DONE      |NOSIGNATURE
		MekanismTools-1.16.5-10.0.21.448.jar              |Mekanism: Tools               |mekanismtools                 |10.0.21             |DONE      |NOSIGNATURE
		workshopsofdoom-1.16.4-1.1.0.1.jar                |Workshops of Doom             |workshopsofdoom               |1.1.0.1             |DONE      |NOSIGNATURE
		LibVulpes-1.16.5-1.0.1-universal.jar              |Lib Vulpes                    |libvulpes                     |1.16.5-1.0.1        |DONE      |NOSIGNATURE
		hunterillager-1.16.4-1.2.0.jar                    |HunterIllager                 |hunterillager                 |1.16.4-1.2.0        |DONE      |NOSIGNATURE
		wandering_trapper-1.16.2-0.1.1.jar                |Wandering Trapper             |wandering_trapper             |1.16.2-0.1.0        |DONE      |NOSIGNATURE
		Vampirism-1.16.4-1.7.8.jar                        |Vampirism                     |vampirism                     |1.7.8               |DONE      |NOSIGNATURE
		VampirismIntegrations-1.16.4-1.5.0.jar            |Vampirism Integrations        |vampirism_integrations        |1.5.0               |DONE      |NOSIGNATURE
		mvw-1.7.0.jar                                     |MoreVanillaWeapons            |mvw                           |1.16.X-1.6.1        |DONE      |NOSIGNATURE
		guardscraft-1.16.5-1.0.0.jar                      |GuardsCraft                   |guardscraft                   |1.16.5-1.0.0        |DONE      |NOSIGNATURE
		enchantwithmob-1.16.4-2.3.1.jar                   |Enchant With Mob              |enchantwithmob                |1.16.4-2.3.1        |DONE      |NOSIGNATURE
		LegendOfHerobrine-1.16.4_1.16.5-0.5.4.jar         |The Legend of Herobrine       |herobrine                     |0.5.4               |DONE      |NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0.jar                   |GeckoLib                      |geckolib3                     |3.0.0               |DONE      |NOSIGNATURE
	Crash Report UUID: c09d59b1-3f92-4c95-a185-0c793824c141
	Launched Version: 1.16.5-forge-36.0.46
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.63, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/ComplementaryResources 3.12.zip, file/Glas+ 1.15.2 (+ Colored glass).zip (incompatible)
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 4800H with Radeon Graphics 
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: 20210117-013236
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryShaders_3.12.zip
	OpenGlVersion: 4.6.0 NVIDIA 457.63
	OpenGlRenderer: GeForce GTX 1660 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by Csquaredaap** [comment]
Here is a crash report i managed 2 get

**Comment by ogzander** [comment]
For your version you list 1.16..
If so, that's your problem. From what I can tell Advanced Rocketry is only available for 1.12.2

**Comment by Csquaredaap** [comment]
No there is a 1.16 version but they say it is a little buggy..... And it works fine on its own but when I try using it with other mods it crashes when u hold any items from the mod or wont load the world at all

**Comment by ogzander** [comment]
Oh my mistake, didn't see the upload for 1.16.
From what I can tell there is an issue with LazyOptional, and wants it to return Empty() instead of null, which might require zmaster to fix.
For the time being try and remove immersive engineering and test that

**Comment by Csquaredaap** [comment]
Ill try it...... How can u tell that its that 1? All i see is..... Idk what I see 😅

**Comment by Csquaredaap** [comment]
Oh nvm i see it now

**Comment by FynnWaelsing** [comment]
I can verify that using certain mods with the latest AR (Advanced Rocketry 1.16.5-1.7.1-3 build -3 for 1.16.5) and LibVulpes (LibVulpes 1.16.5-1.0.1-4 build -4 for 1.16.5) causes worldgen hang when creating a new world. It freezes at 100% and never finishes generating. No crash report is generated. Here are the other mods I have installed:

AutoRegLib-1.6-47.jar
Quark-r2.4-308.jar
jei-1.16.5-7.6.1.75.jar

Removing Quark and AutoRegLib appears to fix the issue.

**Comment by zmaster587** [comment]
@FynnWaelsing Could you post the debug.log for when it hangs?

**Comment by zmaster587** [comment]
Followup on the hang at 100%, it looks like it's deadlocking while getting a tileentity.  Pretty much the same stack trace as this here: https://github.com/Vazkii/Quark/issues/2922#issuecomment-785149708

Looks like it may be the same type of issue.  I'll have to poke at the CableTickHandler, which... shouldn't be there at all???

```
Unsafe.park(boolean, long) line: not available [native method]	
LockSupport.parkNanos(Object, long) line: 234	
ServerChunkProvider$ChunkExecutor(ThreadTaskExecutor<R>).func_223705_bi() line: 139	
ServerChunkProvider$ChunkExecutor(ThreadTaskExecutor<R>).func_213161_c(BooleanSupplier) line: 129	
ServerChunkProvider.func_212849_a_(int, int, ChunkStatus, boolean) line: 130	
ServerWorld(World).func_217353_a(int, int, ChunkStatus, boolean) line: 167	
ServerWorld(IWorldReader).func_217348_a(int, int, ChunkStatus) line: 112	
ServerWorld(World).func_212866_a_(int, int) line: 163	
ServerWorld(World).func_175726_f(BlockPos) line: 159	
ServerWorld(World).func_175690_a(BlockPos, TileEntity) line: 639	
Chunk.func_150813_a(TileEntity) line: 401	
Chunk.func_212815_a(BlockPos, CompoundNBT) line: 734	
Chunk.func_177424_a(BlockPos, Chunk$CreateEntityType) line: 381	
Chunk.func_175625_s(BlockPos) line: 368	
CableTickHandler.chunkLoadedEvent(ChunkEvent$Load) line: 44	
ASMEventHandler_218_CableTickHandler_chunkLoadedEvent_Load.invoke(Event) line: not available	
ASMEventHandler.invoke(Event) line: 85	
1398916488.invoke(IEventListener, Event) line: not available	
EventBus.post(Event, IEventBusInvokeDispatcher) line: 302	
EventBus.post(Event) line: 283	
ChunkManager.func_219237_a_(ChunkHolder, IChunk) line: 605	
1291857919.apply(Object) line: not available	
Either<L,R>.lambda$mapLeft$0(Function, Object) line: 162	
499056362.apply(Object) line: not available	
Either$Left<L,R>.map(Function<? super L,? extends T>, Function<? super R,? extends T>) line: 38	
Either$Left<L,R>(Either<L,R>).mapLeft(Function<? super L,? extends T>) line: 162	
ChunkManager.func_219193_a_(ChunkHolder, Either) line: 569	
1893084630.apply(Object) line: not available	
CompletableFuture$UniApply<T,V>.tryFire(int) line: 642	
CompletableFuture$UniApply<T,V>(CompletableFuture$Completion).run() line: 478	
ChunkTaskPriorityQueueSorter.func_219083_b(Runnable, ITaskExecutor) line: 58	
554117378.run() line: not available	
ServerChunkProvider$ChunkExecutor(ThreadTaskExecutor<R>).func_213166_h(R) line: 144	
ServerChunkProvider$ChunkExecutor.func_213166_h(Runnable) line: 514	
ServerChunkProvider$ChunkExecutor(ThreadTaskExecutor<R>).func_213168_p() line: 118	
ServerChunkProvider$ChunkExecutor.func_213168_p() line: 522	
ServerChunkProvider.func_217234_d() line: 267	
IntegratedServer(MinecraftServer).func_213205_aW() line: 722	
IntegratedServer(MinecraftServer).func_213168_p() line: 711	
IntegratedServer(ThreadTaskExecutor<R>).func_213161_c(BooleanSupplier) line: 127	
IntegratedServer(MinecraftServer).func_213202_o() line: 697	
IntegratedServer(MinecraftServer).func_213186_a(IChunkStatusListener) line: 469	
IntegratedServer(MinecraftServer).func_240800_l__() line: 310	
IntegratedServer.func_71197_b() line: 60	
IntegratedServer(MinecraftServer).func_240802_v_() line: 621	
MinecraftServer.func_240783_a_(AtomicReference) line: 232	
2123040526.run() line: not available	
Thread.run() line: 834	
```
