### ISSUE TITLE
Fueling Station Crashes When opening GUI

### ISSUE THREAD

**Issue by Csquaredaap** [zmaster587/AdvancedRocketry#2015]
## Version of Advanced Rocketry
1.16

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.16

## Version of Minecraft
1.16.5

## Crash report and log, or VisualVM snapshot (if applicable)
>http://pastebin.com is a good place to put them
>crash reports that are put in the issue itself are impossible to read

> If it's an issue involving lag, please submit a VisualVM sampler snapshot.  Mods like lag goggles cannot provide all of the information needed to debug lag in any useful capacity.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

## Description of the problem

So I built a rocket and i placed down a fueling station, but anytime I right click on it the game immediately crashes. I have the crash report here:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 3/22/21 3:22 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at zmaster587.libVulpes.inventory.modules.ModuleLiquidIndicator.renderBackground(ModuleLiquidIndicator.java:227) ~[?:unspecified] {re:classloading}
	at zmaster587.libVulpes.inventory.GuiModular.func_230450_a_(GuiModular.java:209) ~[?:unspecified] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:88) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at zmaster587.libVulpes.inventory.GuiModular.func_230430_a_(GuiModular.java:231) ~[?:unspecified] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:296) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:723) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:821) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:mvw.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.46.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$457/2121551683.call(Unknown Source) [forge-1.16.5-36.0.46.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at zmaster587.libVulpes.inventory.modules.ModuleLiquidIndicator.renderBackground(ModuleLiquidIndicator.java:227) ~[?:unspecified] {re:classloading}
	at zmaster587.libVulpes.inventory.GuiModular.func_230450_a_(GuiModular.java:209) ~[?:unspecified] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:88) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at zmaster587.libVulpes.inventory.GuiModular.func_230430_a_(GuiModular.java:231) ~[?:unspecified] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:296) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:723) ~[?:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: zmaster587.libVulpes.inventory.GuiModular
	Mouse location: Scaled: (213, 120). Absolute: (427.000000, 240.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Csquaredaap'/284, l='ClientLevel', x=213.05, y=76.00, z=251.85]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (176,74,208), Chunk: (at 0,4,0 in 11,13; contains blocks 176,0,208 to 191,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 113758 game time, 113758 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.46.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$457/2121551683.call(Unknown Source) [forge-1.16.5-36.0.46.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3691693816 bytes (3520 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.46.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.46.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.46.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.46.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.46.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.46
	FML Language Providers: 
		javafml@36.0
		minecraft@1
		kotlinforforge@1.10.0
	Mod List: 
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |DONE      |NOSIGNATURE
		mining-helmet-1.16.4-2.0.0.jar                    |Mining Helmet                 |mining_helmet                 |2.0.0               |DONE      |NOSIGNATURE
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |DONE      |NOSIGNATURE
		kingvillager-1.6.1.jar                            |The King of the villagers     |kingvillager                  |1.6.1               |DONE      |NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.0.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.0      |DONE      |NOSIGNATURE
		looot-1.16.4-1.0.0.3.jar                          |Looot                         |looot                         |1.0.0.3             |DONE      |NOSIGNATURE
		colytra-forge-1.16.4-5.1.0.0.jar                  |Colytra                       |colytra                       |1.16.4-5.1.0.0      |DONE      |NOSIGNATURE
		Guide-API-VP-1.16.4-2.2.1.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.1               |DONE      |NOSIGNATURE
		extraboats-1.16.5-2.1.0.jar                       |Extra Boats                   |extraboats                    |2.1.0               |DONE      |NOSIGNATURE
		Space-Bosstools-1.16.4-4.6.jar                    |Space-Bosstools               |boss_tools                    |4.4                 |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		appliedenergistics2-8.2.0.jar                     |Applied Energistics 2         |appliedenergistics2           |8.2.0               |DONE      |95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		TravelersBackpack-1.16.5-5.4.0.jar                |Traveler's Backpack           |travelersbackpack             |5.4.0               |DONE      |NOSIGNATURE
		PlayerMobs-1.0.5.7.jar                            |Player Mobs                   |player_mobs                   |1.0.5.7             |DONE      |15:a4:a3:0e:d2:f8:64:0c:a4:97:30:5f:48:ba:5f:69:f9:23:42:14:a8:5a:60:3a:b1:b1:29:1a:0a:37:3c:79
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		Guard-Villagers-Mod-1.16.4.jar                    |Guard Villagers               |guardvillagers                |1.1.8               |DONE      |NOSIGNATURE
		simpleplanes-1.16.4-4.1.2.jar                     |Simple Planes                 |simpleplanes                  |1.16.4-4.1.2        |DONE      |NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		PiratesAndLootersMod7.0-1.16.4.jar                |Pirates_And_Looters_Mod       |pirates_and_looters_mod       |1.0.0               |DONE      |NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.2.0-3.jar             |Immersive Petroleum           |immersivepetroleum            |3.2.0-3             |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.46-universal.jar                |Forge                         |forge                         |36.0.46             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		scuba-gear-1.16.5-1.0.2.jar                       |Scuba Gear                    |scuba_gear                    |1.0.2               |DONE      |NOSIGNATURE
		refinedstorage-1.9.12.jar                         |Refined Storage               |refinedstorage                |1.9.12              |DONE      |NOSIGNATURE
		structure_gel-1.16.4-1.7.5.jar                    |Structure Gel API             |structure_gel                 |1.7.5               |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.46-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		customizableelytra-1.16.4-1.3.0.jar               |Customizable Elytra           |customizableelytra            |1.3.0               |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.5-4.2.4-134.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-4.2.4-134    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		MekanismAdditions-1.16.5-10.0.21.448.jar          |Mekanism: Additions           |mekanismadditions             |10.0.21             |DONE      |NOSIGNATURE
		Numina-1.16.4-2.0.4.jar                           |Numina                        |numina                        |2.0.4               |DONE      |NOSIGNATURE
		ModularPowersuits-1.16.4-2.0.2.jar                |MachineMuse's Modular Powersui|powersuits                    |1.0.0               |DONE      |NOSIGNATURE
		AdvancedRocketry-1.16.5-1.7.1-4-universal.jar     |Advanced Rocketry             |advancedrocketry              |1.16.5-1.7.1-4      |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.71.jar                           |Just Enough Items             |jei                           |7.6.1.71            |DONE      |NOSIGNATURE
		wardance-0.3.3.jar                                |Project: War Dance            |wardance                      |0.3.3               |DONE      |NOSIGNATURE
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.0      |DONE      |NOSIGNATURE
		Artifacts-1.16.5-2.8.3.jar                        |Artifacts                     |artifacts                     |1.16.5-2.8.3        |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		FluxNetworks-1.16.5-6.1.6.11.jar                  |Flux Networks                 |fluxnetworks                  |1.16.5-6.1.6.11     |DONE      |NOSIGNATURE
		backpacked-1.7.0-1.16.3.jar                       |Backpacked                    |backpacked                    |1.7.0               |DONE      |NOSIGNATURE
		backpacker-1.2.2-1.16.3.jar                       |Backpacker                    |backpacker                    |1.2.2               |DONE      |NOSIGNATURE
		moarboats-1.16.3-8.0.0.0-beta3.jar                |Moar Boats                    |moarboats                     |1.16.3-8.0.0.0-beta3|DONE      |NOSIGNATURE
		illagersweararmor-1.0.3.jar                       |Illagers Wear Armor           |illagersweararmor             |1.0.3               |DONE      |NOSIGNATURE
		obfuscate-0.6.0-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.0               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		vehicle-0.45.1-mc1.16.3.jar                       |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.1              |DONE      |NOSIGNATURE
		Desolation+1.0.5b+1.16.5.jar                      |Desolation (Forge)            |desolation                    |1.0.5b              |DONE      |NOSIGNATURE
		Undercover+Witches+1.0.1.jar                      |Undercover Witches            |undercoverwitches             |1.0.1               |DONE      |NOSIGNATURE
		MekanismTools-1.16.5-10.0.21.448.jar              |Mekanism: Tools               |mekanismtools                 |10.0.21             |DONE      |NOSIGNATURE
		workshopsofdoom-1.16.4-1.1.0.1.jar                |Workshops of Doom             |workshopsofdoom               |1.1.0.1             |DONE      |NOSIGNATURE
		LibVulpes-1.16.5-1.0.1-universal.jar              |Lib Vulpes                    |libvulpes                     |1.16.5-1.0.1        |DONE      |NOSIGNATURE
		hunterillager-1.16.4-1.2.0.jar                    |HunterIllager                 |hunterillager                 |1.16.4-1.2.0        |DONE      |NOSIGNATURE
		wandering_trapper-1.16.2-0.1.1.jar                |Wandering Trapper             |wandering_trapper             |1.16.2-0.1.0        |DONE      |NOSIGNATURE
		cfm-7.0.0-pre19-mc1.16.3.jar                      |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |NOSIGNATURE
		Vampirism-1.16.4-1.7.8.jar                        |Vampirism                     |vampirism                     |1.7.8               |DONE      |NOSIGNATURE
		VampirismIntegrations-1.16.4-1.5.0.jar            |Vampirism Integrations        |vampirism_integrations        |1.5.0               |DONE      |NOSIGNATURE
		Infinitylib-2.0.2.jar                             |InfinityLib                   |infinitylib                   |1.16.5-2.0.2        |DONE      |NOSIGNATURE
		ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar     |Immersive Railroading         |immersiverailroading          |1.16.4-forge-1.8.0  |DONE      |NOSIGNATURE
		UniversalModCore-1.16.4-forge-1.0.1.jar           |Universal Mod Core            |universalmodcore              |1.0.1               |DONE      |NOSIGNATURE
		engineersdecor-1.16.4-1.1.9.jar                   |Engineer's Decor              |engineersdecor                |1.1.9               |DONE      |bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		lantern-2.0.1.jar                                 |Lantern                       |lantern                       |1.16.5-2.0.1        |DONE      |NOSIGNATURE
		mvw-1.7.0.jar                                     |MoreVanillaWeapons            |mvw                           |1.16.X-1.6.1        |DONE      |NOSIGNATURE
		enchantwithmob-1.16.4-2.3.1.jar                   |Enchant With Mob              |enchantwithmob                |1.16.4-2.3.1        |DONE      |NOSIGNATURE
		LegendOfHerobrine-1.16.4_1.16.5-0.5.4.jar         |The Legend of Herobrine       |herobrine                     |0.5.4               |DONE      |NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0.jar                   |GeckoLib                      |geckolib3                     |3.0.0               |DONE      |NOSIGNATURE
	Crash Report UUID: 673695e0-2a32-4a45-b0f2-868950ca8c21
	Launched Version: 1.16.5-forge-36.0.46
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.63, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: renderer: Stencil enabled in Immersive Engineering config
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 4800H with Radeon Graphics 
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: 20210117-013236
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.63
	OpenGlRenderer: GeForce GTX 1660 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by Csquaredaap** [comment]
Also I want to thank you for fixing the issue I reported the other day..... #2010! I really appreciate you helping me out :P

**Comment by Csquaredaap** [comment]
I tried bypassing using the GUI screen by using a hopper to put fuel in and it immediately crashed with an error code 0..... so im guessing there may not be a way for me to fuel my rocket 😅

**Comment by criv5** [comment]
Been having the same crash as well.

**Comment by zmaster587** [comment]
Should be fixed by https://github.com/Advanced-Rocketry/libVulpes/commit/d5bb838e8a780b6c14028a8ab42809e67ba309ae

LibVulpes-1.16.5-1.0.1-2-universal.jar and later
