### ISSUE TITLE
can't log into server after crash during build

### ISSUE THREAD

**Issue by DragarX** [zmaster587/AdvancedRocketry#2046]
## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-1.7.1-8-universal.jar

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
LibVulpes-1.16.5-1.0.1-14-universal.jar

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
Unsure

## Description of the problem
When I built my rocket, my server crashed. Upon restarting I get this error whenever I try to log in.

> [06.04 10:34:38] [Server] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for ******
[06.04 10:34:38] [Server] java.lang.RuntimeExceptionAttempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
[06.04 10:34:38] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.1.4.jar:36.{}
[06.04 10:34:38] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
[06.04 10:34:38] [Server] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
[06.04 10:34:38] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
[06.04 10:34:38] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
[06.04 10:34:38] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
[06.04 10:34:38] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_{}
[06.04 10:34:38] [Server] 	at ) ~[advancedrocketry:unspecified] {re:classloading,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.world.TrackedEntity.func_219452_a(TrackedEntity.java:204) ~[?:?] {re:mixin,re:classloading,xf:fml:twilightforest:sync,pl:mixin:APP:abnormals_core.mixins.json:TrackedEntityMixin,pl:mixin:APP:endergetic.mixins.json:TrackedEntityMixin,pl:mixin:A}
[06.04 10:34:38] [Server] 	at net.minecraft.world.TrackedEntity.func_219455_b(TrackedEntity.java:193) ~[?:?] {re:mixin,re:classloading,xf:fml:twilightforest:sync,pl:mixin:APP:abnormals_core.mixins.json:TrackedEntityMixin,pl:mixin:APP:endergetic.mixins.json:TrackedEntityMixin,pl:mixin:A}
[06.04 10:34:38] [Server] 	at net.minecraft.world.server.ChunkManager$EntityTracker.func_219400_b(ChunkManager.java:1155) ~[?:?] {re:classloading}
[06.04 10:34:38] [Server] 	at net.minecraft.world.server.ChunkManager.func_219180_a(ChunkManager.java:1049) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftbchunks.mixins.json:ChunkMapMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.world.server.ChunkManager.func_219199_a(ChunkManager.java:746) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftbchunks.mixins.json:ChunkMapMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.world.server.ChunkManager.func_219234_a(ChunkManager.java:845) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftbchunks.mixins.json:ChunkMapMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.world.server.ChunkManager.func_219210_a(ChunkManager.java:961) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftbchunks.mixins.json:ChunkMapMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.world.server.ServerChunkProvider.func_217230_c(ServerChunkProvider.java:453) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.world.server.ServerWorld.func_217465_m(ServerWorld.java:933) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.world.server.ServerWorld.func_217448_f(ServerWorld.java:803) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.world.server.ServerWorld.func_217435_c(ServerWorld.java:780) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:184) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:endergetic.mixins.json:PlayerListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:classloading}
[06.04 10:34:38] [Server] 	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:classloading}
[06.04 10:34:38] [Server] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
[06.04 10:34:38] [Server] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.04 10:34:38] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_{}

**Comment by DragarX** [comment]
This is what the server reports on login

> [06.04 10:42:44] [Server] [Netty Epoll Server IO #15/ERROR] [minecraft/ArgumentTypes]: Could not serialize zmaster587.advancedRocketry.command.StarArgument@55b92376 (class zmaster587.advancedRocketry.command.StarArgument) - will not be sent to client!
[06.04 10:42:44] [Server] [Netty Epoll Server IO #15/ERROR] [minecraft/ArgumentTypes]: Could not serialize zmaster587.advancedRocketry.command.ReflectionArgument@46cc7b92 (class zmaster587.advancedRocketry.command.ReflectionArgument) - will not be sent to client!
[06.04 10:42:44] [Server] [Netty Epoll Server IO #15/ERROR] [minecraft/ArgumentTypes]: Could not serialize zmaster587.advancedRocketry.command.ReflectionArgument@1c7f0287 (class zmaster587.advancedRocketry.command.ReflectionArgument) - will not be sent to client!
[06.04 10:42:44] [Server] [Netty Epoll Server IO #15/ERROR] [minecraft/ArgumentTypes]: Could not serialize zmaster587.advancedRocketry.command.ReflectionArgument@5b95ec19 (class zmaster587.advancedRocketry.command.ReflectionArgument) - will not be sent to client!
[06.04 10:42:44] [Server] [Netty Epoll Server IO #15/ERROR] [minecraft/ArgumentTypes]: Could not serialize zmaster587.advancedRocketry.command.ReflectionArgument@2bdf66d1 (class zmaster587.advancedRocketry.command.ReflectionArgument) - will not be sent to client!

**Comment by zmaster587** [comment]
Would you be able to post the crash report you got when you built the rocket (it should still be in the crash-reports folder) and the full server log containing the error you got there?  Could you also use a site like pastebin to put them?  They're pretty hard to read on github.

**Comment by DragarX** [comment]
Crashlog https://pastebin.com/77ckPqBw
Serverlog 
[crash-2021-04-06_10.08.32-server.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6277340/crash-2021-04-06_10.08.32-server.txt)

**Comment by zmaster587** [comment]
Only occurred on servers, but should be fixed now
