### ISSUE TITLE
[BUG] Serious Log Inflation + Crash with ArchitectureCraft

### ISSUE THREAD

**Issue by oliverrook** [zmaster587/AdvancedRocketry#2120]
## Version of Advanced Rocketry
>1.12.2-1.7.0-232

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
>1.12.2-0.4.2-75

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y
- Advanced Rocketry
- ArchitectureCraft
- Possibly Optifine (Since it mentioned Rendering)
- Possibly Colored Lux (Since it mentioned lighting)

## Crash report or log or visualVM (if applicable)
> Not possible due to how fast the log file inflates (over a dozen megabytes a second.) Repeated error below

The error that it repeats:
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4442)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4209]: Something just went wrong here, getting default light value instead!
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: java.lang.IllegalStateException: We can't be accessing this manager since WorldEvent.load() was never called!
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.world.World.getManager(World.java:7517)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at org.valkyrienskies.mod.common.util.ValkyrienUtils.getPhysObjWorld(ValkyrienUtils.java:208)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.world.World.handler$zbm000$preGetCombinedLight(World.java:4162)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.world.World.func_175626_b(World.java)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.block.Block.func_185484_c(Block.java:378)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185889_a(BlockStateContainer.java:367)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at team.chisel.ctm.client.state.CTMExtendedState.func_185889_a(CTMExtendedState.java:37)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.func_187491_a(BlockModelRenderer.java:749)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:190)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:128)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:85)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:79)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:58)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at com.elytradev.architecture.client.render.CustomBlockDispatcher.func_175018_a(CustomBlockDispatcher.java:98)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at zmaster587.advancedRocketry.client.render.RendererRocket.func_76986_a(RendererRocket.java:149)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.RenderGlobal.redirect$zel000$renderEntityStatic(RenderGlobal.java:4753)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:849)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
[15:44:23] [Client thread/INFO]: [net.minecraft.world.World:handler$zbm000$preGetCombinedLight:4210]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)

## Description of the problem
> When using ArchitectureCraft blocks in a Rocket, upon completion of building the rocket, the game freezes completely and the log file begins to inflate rapidly at a rate of over 10 Mb/s. I managed to stop it before it got too big to open, but it is still too big to upload. I will post the error before it repeats above.

**Comment by voidsong-dragonfly** [comment]
Try with _just_ AR and ArchitectureCraft. We're not people with infinite time, it's not our job to deal with narrowing down mod interactions.
