### ISSUE TITLE
Superflat world hang error

### ISSUE THREAD

**Issue by BrisingrAerowing** [zmaster587/AdvancedRocketry#219]
```java.lang.NullPointerException
	at zmaster587.advancedRocketry.atmosphere.AtmosphereHandler.onBlockChange(AtmosphereHandler.java:158) ~[AtmosphereHandler.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:351) ~[aid.class:?]
	at lumien.randomthings.worldgen.WorldGenPlants.generate(WorldGenPlants.java:32) ~[WorldGenPlants.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120) ~[GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001) ~[asv.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:969) ~[asv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) ~[lr.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) ~[aid.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) ~[aid.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:842) ~[aid.class:?]
	at com.hea3ven.buildingbricks.compat.vanilla.GrassSlabWorldGen.onPopulateChunkPreEvent(GrassSlabWorldGen.java:87) ~[GrassSlabWorldGen.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_117_GrassSlabWorldGen_onPopulateChunkPreEvent_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:589) [ForgeEventFactory.class:?]
	at net.minecraft.world.gen.ChunkProviderFlat.func_185931_b(ChunkProviderFlat.java:178) [aty.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000) [asv.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974) [asv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) [lr.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) [aid.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) [aid.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:842) [aid.class:?]
	at net.minecraft.world.World.func_175623_d(World.java:223) [aid.class:?]
	at com.pam.harvestcraft.blocks.blocks.BlockBaseGarden.func_176196_c(BlockBaseGarden.java:105) [BlockBaseGarden.class:?]
	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generateGarden(BushWorldWorldGen.java:72) [BushWorldWorldGen.class:?]
	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generate(BushWorldWorldGen.java:57) [BushWorldWorldGen.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120) [GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001) [asv.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:969) [asv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) [lr.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) [aid.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) [aid.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:842) [aid.class:?]
	at net.minecraft.world.World.func_175623_d(World.java:223) [aid.class:?]
	at net.minecraft.world.World.func_184141_c(World.java:203) [aid.class:?]
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:67) [atl.class:?]
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:950) [ls.class:?]
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:872) [ls.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:87) [bzl.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
```

When trying to build a superflat world with no decoration, the game hangs and the above exception is spat out into the logs.

**Comment by zmaster587** [comment]
Can you provide the full log?  And does this still occur without pams?

**Comment by BrisingrAerowing** [comment]
It only occurs with AR installed. Pams Harvestcraft doesn't crash. I tried with only AR and got a similar crash.

I just noticed that the exception was lost. It was a NullPointerException.

I'll find the full log.

**Comment by BrisingrAerowing** [comment]
[Client and Crash logs](https://gist.github.com/BrisingrAerowing/5bdb25d877f7034524eb457934c17085)

**Comment by zmaster587** [comment]
The only way this should be able to happen is if for some reason world gen occurs before the world load event is fired... investigating

**Comment by zmaster587** [comment]
I'm still unable to replicate it with only AR and libvulpes installed, can you get me the crashlog from when only the two are installed.
What I have tried:  Super flat world, with all combinations of bonus chest and world structures.

It would be extremely helpful if you could lay out how to replicate it with just AR and libvulpes

**Comment by zmaster587** [comment]
Confirmed, World begins generating in super flat worlds BEFORE firing the onWorldLoad event...
