### ISSUE TITLE
[BUG] Rocket Assembler Not Opening And Crashing World When World Reloaded

### ISSUE THREAD

**Issue by Half-A-Shilling** [zmaster587/AdvancedRocketry#2262]
rocket assembler is inaccessible without any mods installed at all other than the latest versions of libvulpes and advanced rocketry 

## Version of Advanced Rocketry
>AdvancedRocketry-1.16.5-2.0.0-16-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>LibVulpes-1.16.5-1.0.2-1-universal

## Version of Minecraft
>1.16.5

## Does this occur without other mods installed

- [x] Y

## Crash report or log or visualVM (if applicable)
>https://paste-bin.xyz/14409

## Description of the problem
>The crash log is produced after the world has been reloaded with a rocket assembler placed down, The issue seems to start with the rocket assembler, which is completely inaccessible, right clicking simply doesnt provide a UI or interface, the space station assembler works fine, the satellite builder doesnt seem to have any right click functionality, it just acts as a normal block, the mods mentioned in the crash log are Flywheel, astral sorcery, twilight forest, observer lib, integrated proxies, and roadrunner. It is unlikely that flywheel is the issue, as the create above and beyond pack has rocket assemblers working. If this is all too much please ignore, thank you very much for the help

**Comment by Migmag789** [comment]
I have the same issue.

**Comment by ghost** [comment]
Same issue. It was originally caused by having Roadrunner (Lithium) installed. Removing Roadrunner allows the game to play without crashing, but AR now seems to be in some broken state where nothing works. The rocket assembler UI won't open, it's just an inert block wherever it is placed. I've tried deleting the ARdata.dat file, no change. I've tried completely disassembling the rocket and launchpad, saving and reloading the game, and then rebuilding it elsewhere, no change. I cheated my way into creative mode and got a new assembler block, no change. 

Trying to open the assembler UI outputs the following to the log:

`[23Nov2021 16:25:50.720] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.util.IllegalFormatConversionException: d != java.lang.Float
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302) ~[?:1.8.0_242]
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793) ~[?:1.8.0_242]
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747) ~[?:1.8.0_242]
	at java.util.Formatter.format(Formatter.java:2520) ~[?:1.8.0_242]
	at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_242]
	at java.lang.String.format(String.java:2940) ~[?:1.8.0_242]
	at zmaster587.advancedRocketry.tile.TileRocketAssemblingMachine.updateText(TileRocketAssemblingMachine.java:774) ~[advancedrocketry:unspecified]
	at zmaster587.advancedRocketry.tile.TileRocketAssemblingMachine.getModules(TileRocketAssemblingMachine.java:815) ~[advancedrocketry:unspecified]
	at zmaster587.advancedRocketry.tile.TileRocketAssemblingMachine.createMenu(TileRocketAssemblingMachine.java:1056) ~[advancedrocketry:unspecified]
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:226) ~[forge:?]
	at zmaster587.libVulpes.block.BlockTile.func_225533_a_(BlockTile.java:76) ~[libvulpes:unspecified]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:338) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[23Nov2021 16:25:52.057] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer/]: Saving and pausing game...
[23Nov2021 16:25:52.085] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Create A&B]'/minecraft:overworld
[23Nov2021 16:25:52.270] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Create A&B]'/minecraft:the_nether
[23Nov2021 16:25:52.276] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Create A&B]'/minecraft:the_end
[23Nov2021 16:25:52.278] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Create A&B]'/advancedrocketry:space
[23Nov2021 16:25:52.279] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Create A&B]'/custommoon:moon
`

**Comment by voidsong-dragonfly** [comment]
Yeah, we know the UI's broke. The mod's in alpha, what did you expect. We've fixed this, the build system is going to release at some point. Just wait until then.
