### ISSUE TITLE
crash on client

### ISSUE THREAD

**Issue by wlich** [zmaster587/AdvancedRocketry#267]
i start my world ...and minecraft is crashed 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-0.9.1.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 28.10.16 21:04
Description: Updating screen events

java.lang.IllegalStateException: failed to create a child event loop
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68)
    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
    at net.minecraft.network.NetworkSystem$1.func_179280_b(NetworkSystem.java:53)
    at net.minecraft.network.NetworkSystem$1.func_179280_b(NetworkSystem.java:50)
    at net.minecraft.util.LazyLoadBase.func_179281_c(SourceFile:10)
    at net.minecraft.network.NetworkSystem.func_151270_a(NetworkSystem.java:140)
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2343)
    at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:460)
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:408)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:128)
    at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120)
    at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87)
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
    ... 23 more
Caused by: java.io.IOException: Unable to establish loopback connection
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.nio.ch.PipeImpl.<init>(Unknown Source)
    at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
    at java.nio.channels.Pipe.open(Unknown Source)
    at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
    at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126)
    ... 26 more
Caused by: java.net.ConnectException: Connection timed out: connect
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Unknown Source)
    at sun.nio.ch.Net.connect(Unknown Source)
    at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
    at java.nio.channels.SocketChannel.open(Unknown Source)
    at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(Unknown Source)
    ... 35 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68)
    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
    at net.minecraft.network.NetworkSystem$1.func_179280_b(NetworkSystem.java:53)
    at net.minecraft.network.NetworkSystem$1.func_179280_b(NetworkSystem.java:50)
    at net.minecraft.util.LazyLoadBase.func_179281_c(SourceFile:10)
    at net.minecraft.network.NetworkSystem.func_151270_a(NetworkSystem.java:140)
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2343)
    at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:460)
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:408)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.GuiScreenWorking
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_111, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 411626840 bytes (392 MB) / 789790720 bytes (753 MB) up to 951320576 bytes (907 MB)
    JVM Flags: 5 total; -Xmx920M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.2.2114 10 mods loaded, 10 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2114.jar) 
    UCHIJAAAA   Forge{12.18.2.2114} [Minecraft Forge](forge-1.10.2-12.18.2.2114.jar) 
    UCHIJAAAA   AdvancedRocketry{1} [Advanced Rocketry](minecraft.jar) 
    UCHIJAAAA   libVulpes{0.1.5.20161016002555} [libVulpes](LibVulpes-1.10.2-0.1.5-universal.jar) 
    UCHIJAAAA   advancedRocketry{1.10.2-0.9.1} [Advanced Rocketry](AdvancedRocketry-1.10.2-0.9.1.jar) 
    UCHIJAAAA   CodeChickenLib{2.4.3.124} [CodeChicken Lib](CodeChickenLib-1.10.2-2.4.3.124-universal.jar) 
    UCHIJAAAA   CodeChickenCore{2.3.5.91} [CodeChicken Core](CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
    UCHIJAAAA   rftools{5.57} [RFTools](rftools-1.10-5.57.jar) 
    UCHIJAAAA   rftoolsdim{4.43} [RFTools Dimensions](rftoolsdim-1.10-4.43.jar) 
    Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-0.9.1.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)

```
GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.11399 Compatibility Profile Context' Renderer: 'AMD Radeon HD 6470M'
Launched Version: 1.10.2-forge1.10.2-12.18.2.2114
LWJGL: 2.9.4
OpenGL: AMD Radeon HD 6470M GL version 4.2.11399 Compatibility Profile Context, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: Русский (Россия)
Profiler Position: N/A (disabled)
CPU: 2x AMD E-450 APU with Radeon(tm) HD Graphics
```

**Comment by zmaster587** [comment]
From this it looks like your connection timed out, or the server thread hung, do you have a full startup log (fml-server-latest.log or fml-client-latest.log)

**Comment by zmaster587** [comment]
Abandoned?
