### ISSUE TITLE
Atmosphere event fired isn't cancelable

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#275]
https://github.com/zmaster587/AdvancedRocketry/blob/MC1_10/src/main/java/zmaster587/advancedRocketry/atmosphere/AtmosphereHandler.java#L93

Here it should make an AtmosphereTickEvent instead of an AtmosphereEvent, otherwise the following occurs when I try to cancel it.

`java.lang.IllegalArgumentException: Attempted to cancel a non cancellable event
	at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:93)
	at pokecube.compat.advancedrocketry.AdvancedRocketryCompat.breathe(AdvancedRocketryCompat.java:261)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_107_AdvancedRocketryCompat_breathe_AtmosphereEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at zmaster587.advancedRocketry.atmosphere.AtmosphereHandler.onTick(AtmosphereHandler.java:94)`

**Comment by zmaster587** [comment]
Was a stupid typo on my part...

**Comment by Thutmose** [comment]
no problem, I probably should have noticed that when I looked at when you first added the event.
