### ISSUE TITLE
[Question] Anyone know what to do here?

### ISSUE THREAD

**Issue by xSparky911x** [zmaster587/AdvancedRocketry#351]
```
[17-01-2017 21:47:52] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalArgumentException: timeout value is negative
[17-01-2017 21:47:52] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: at java.lang.Thread.sleep(Native Method)
[17-01-2017 21:47:52] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:83)
[17-01-2017 21:47:52] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: at java.lang.Thread.run(Unknown Source)
[17-01-2017 21:47:52] > Exception in thread "Server Watchdog" Jan 18, 2017 3:47:52 AM zmaster587.advancedRocketry.AdvancedRocketry serverStarting
[17-01-2017 21:47:52] INFO: Checking for config at /home/smpicnic/server/data/./config/advRocketry/planetDefs.xml
```

I tried to look for planetDefs.xml but do not see it anywhere in the advancedrocketry folder.

**Comment by zmaster587** [comment]
Looks like the thread that checks to see if the server hung was asked to
wait for a negative amount of time.  planetDefs.xml is not inclued with AR
by default and if it's not found AR will generate a hardcoded number of
planets with random properties.  So the lack of the xml file should not do
anything funky.    Does this occur if you try to launch again?

On Jan 17, 2017 10:51 PM, "xSparky911x" <notifications@github.com> wrote:

[17-01-2017 21:47:52] [STDERR]:
[java.lang.ThreadGroup:uncaughtException:-1]:
java.lang.IllegalArgumentException: timeout value is negative
[17-01-2017 21:47:52] [STDERR]:
[java.lang.ThreadGroup:uncaughtException:-1]: at
java.lang.Thread.sleep(Native Method)
[17-01-2017 21:47:52] [STDERR]:
[java.lang.ThreadGroup:uncaughtException:-1]: at
net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:83)
[17-01-2017 21:47:52] [STDERR]:
[java.lang.ThreadGroup:uncaughtException:-1]: at
java.lang.Thread.run(Unknown Source)
[17-01-2017 21:47:52] > Exception in thread "Server Watchdog" Jan 18,
2017 3:47:52 AM zmaster587.advancedRocketry.AdvancedRocketry
serverStarting
[17-01-2017 21:47:52] INFO: Checking for config at
/home/smpicnic/server/data/./config/advRocketry/planetDefs.xml

I tried to look for planetDefs.xml but do not see it anywhere in the
advancedrocketry folder.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zmaster587/AdvancedRocketry/issues/351>, or mute the
thread

**Comment by xSparky911x** [comment]
It does yea. Just tried it. Doesn't crash the game or anything but testing this pack on a server, I want to eliminate as many errors as possible :D
