### ISSUE TITLE
ReplayMod Error

### ISSUE THREAD

**Issue by jeremy60800** [zmaster587/AdvancedRocketry#382]
Hey !

The ReplayMod isn't compatible with advanced rocketry ? I try use ReplayMod with AdvancedRocketry but he wirte an error message in a chat : "Failed to start recording" .

So , i check logs and i view this :

`[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: java.lang.IllegalStateException: Duplicate key Wrapped{AdvancedRocketry}
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.stream.Collectors.lambda$throwingMerger$104(Collectors.java:133)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.stream.Collectors$$Lambda$575/932410186.apply(Unknown Source)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.HashMap.merge(HashMap.java:1245)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.stream.Collectors.lambda$toMap$162(Collectors.java:1320)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.stream.Collectors$$Lambda$577/1078956163.accept(Unknown Source)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at com.replaymod.core.utils.ModCompat.getInstalledNetworkMods(ModCompat.java:18)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at com.replaymod.recording.handler.ConnectionEventHandler.onConnectedToServerEvent(ConnectionEventHandler.java:80)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at com.replaymod.recording.ReplayModRecording.initiateRecording(ReplayModRecording.java:61)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at net.minecraft.client.network.NetHandlerLoginClient.handler$replayModRecording_initiateRecording$zza000(NetHandlerLoginClient.java:525)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at net.minecraft.client.network.NetHandlerLoginClient.func_147390_a(NetHandlerLoginClient.java)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at net.minecraft.network.login.server.SPacketLoginSuccess.func_148833_a(SourceFile:39)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at net.minecraft.network.login.server.SPacketLoginSuccess.func_148833_a(SourceFile:11)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[11:59:10] [Netty Client IO #1/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:99]: 	at java.lang.Thread.run(Thread.java:745)
[11:59:10] [Netty Client IO #1/INFO]: [CHAT] [Replay Mod] Failed to start recording`

Thanks :D

**Comment by zmaster587** [comment]
Check if any keybinds conflict with those of AdvancedRocketry.  It looks like something funky is going on with duplicate key registration.

**Comment by jeremy60800** [comment]
I checked and there is no key that is duplicated ... I still have the same error ...

(Sorry for my English , I'm French :D)

**Comment by zmaster587** [comment]
Will see if i can figure it out, at least from what I can tell it's not a super widely used mod and I do have some other things to repair so I'm going to put this in the low priority queue.  It'll probably take me a bit longer to get around to, but I've got a fairly demanding schedule both in modding and outside minecraft (mostly outside...)

**Comment by VoodooBeard** [comment]
I've got this same error, was planning to recording some cool space animatics. Looking forward to it getting fixed :-)

**Comment by zmaster587** [comment]
Turns out replay mod did not like the AR coremod and the mod itself having the same modid
