### ISSUE TITLE
Multiblock and Holo not Showing/Thinking there are more blocks. 

### ISSUE THREAD

**Issue by NPCKiller** [zmaster587/AdvancedRocketry#454]
Orbital Laser Drill Railgun Atmosphere Terraformer Rolling Machine [Red X effected]  Microwave Receiver  Arc Furnace [function effeccted](My Notes)

Im having an Issue with the multiblock on these builds. All but the Arc Furnace and Microwave Show red X's even know they are built the other 2 dont seem to work Properly. (Could be cause Im stupid) 
![2017-03-13_03 16 55](https://cloud.githubusercontent.com/assets/3054712/23845694/05484e7e-07a0-11e7-8952-84942598d30a.png)
![2017-03-13_03 16 49](https://cloud.githubusercontent.com/assets/3054712/23845696/07fe8804-07a0-11e7-9922-adf6d1781549.png)
![2017-03-13_03 16 46](https://cloud.githubusercontent.com/assets/3054712/23845697/0921f892-07a0-11e7-9213-b29d794c3ac8.png)
![2017-03-13_03 16 31](https://cloud.githubusercontent.com/assets/3054712/23845698/0ab0a924-07a0-11e7-85dd-e7bdad858c59.png)
`[03:50:55] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[03:50:55] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[03:50:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[03:50:55] [main/INFO]: Forge Mod Loader version 12.18.3.2254 for Minecraft 1.10.2 loading
[03:50:55] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Users\NPCKillwe\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
[03:50:55] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:50:55] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[03:50:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:50:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:50:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[03:50:57] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[03:50:57] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[03:50:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[03:50:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[03:50:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[03:50:57] [main/ERROR]: A critical problem occurred registering the ASM transformer class 
java.lang.ClassNotFoundException: 
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:46) [forge-1.10.2-12.18.3.2254.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more
[03:50:57] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[03:50:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[03:50:57] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[03:50:58] [Client thread/INFO]: Setting user: NPCKiller
[03:51:01] [Client thread/WARN]: Skipping bad option: lastServer:
[03:51:01] [Client thread/INFO]: LWJGL Version: 2.9.4
[03:51:03] [Client thread/INFO]: [net.minecraftforge.fml.client.SplashProgress:start:223]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.13.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 3/13/17 3:51 AM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 211541952 bytes (201 MB) / 804257792 bytes (767 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.13.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.57' Renderer: 'GeForce GTX 980 Ti/PCIe/SSE2'
[03:51:03] [Client thread/INFO]: MinecraftForge v12.18.3.2254 Initialized
[03:51:03] [Client thread/INFO]: Replaced 231 ore recipes
[03:51:04] [Client thread/INFO]: [zmaster587.advancedRocketry.asm.ModContainer:<init>:21]: ********* CoreDummyContainer. OK
[03:51:04] [Client thread/INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[03:51:04] [Client thread/INFO]: Searching C:\Users\NPCKillwe\Documents\Curse\Minecraft\Instances\Bug Testing\mods for mods
[03:51:05] [Client thread/WARN]: ****************************************
[03:51:05] [Client thread/WARN]: * The modid advancedRocketry is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
[03:51:05] [Client thread/WARN]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:143)
[03:51:05] [Client thread/WARN]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:128)
[03:51:05] [Client thread/WARN]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:51:05] [Client thread/WARN]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[03:51:05] [Client thread/WARN]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:51:05] [Client thread/WARN]: *  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)...
[03:51:05] [Client thread/WARN]: ****************************************
[03:51:05] [Client thread/WARN]: ****************************************
[03:51:05] [Client thread/WARN]: * The modid libVulpes is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
[03:51:05] [Client thread/WARN]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:143)
[03:51:05] [Client thread/WARN]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:128)
[03:51:05] [Client thread/WARN]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:51:05] [Client thread/WARN]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[03:51:05] [Client thread/WARN]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:51:05] [Client thread/WARN]: *  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)...
[03:51:05] [Client thread/WARN]: ****************************************
[03:51:05] [Client thread/INFO]: Forge Mod Loader has identified 6 mods to load
[03:51:05] [Client thread/INFO]: [zmaster587.advancedRocketry.asm.ModContainer:registerBus:40]: ********* registerBus. OK
[03:51:05] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, AdvancedRocketryCore, advancedRocketry, libVulpes] at CLIENT
[03:51:05] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, AdvancedRocketryCore, advancedRocketry, libVulpes] at SERVER
[03:51:05] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Advanced Rocketry, FMLFileResourcePack:libVulpes
[03:51:06] [Client thread/INFO]: Processing ObjectHolder annotations
[03:51:06] [Client thread/INFO]: Found 423 ObjectHolder annotations
[03:51:06] [Client thread/INFO]: Identifying ItemStackHolder annotations
[03:51:06] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[03:51:06] [Thread-6/INFO]: Using sync timing. 200 frames of Display.update took 92291483 nanos
[03:51:06] [Client thread/INFO]: Applying holder lookups
[03:51:06] [Client thread/INFO]: Holder lookups applied
[03:51:06] [Client thread/INFO]: Applying holder lookups
[03:51:06] [Client thread/INFO]: Holder lookups applied
[03:51:06] [Client thread/INFO]: Applying holder lookups
[03:51:06] [Client thread/INFO]: Holder lookups applied
[03:51:06] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[03:51:06] [Forge Version Check/INFO]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[03:51:06] [Forge Version Check/INFO]: [Forge] Found status: AHEAD Target: null
[03:51:06] [Client thread/INFO]: OBJLoader: Domain advancedrocketry has been added.
[03:51:07] [Client thread/INFO]: Applying holder lookups
[03:51:07] [Client thread/INFO]: Holder lookups applied
[03:51:07] [Client thread/INFO]: Injecting itemstacks
[03:51:07] [Client thread/INFO]: Itemstack injection complete
[03:51:08] [Sound Library Loader/INFO]: Starting up SoundSystem...
[03:51:08] [Thread-8/INFO]: Initializing LWJGL OpenAL
[03:51:08] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[03:51:08] [Client thread/INFO]: OBJLoader.Parser: command 's' (model: 'advancedrocketry:models/block/models/advRocketmotor.obj') is not currently supported, skipping. Line: 347 's off'
[03:51:08] [Thread-8/INFO]: OpenAL initialized.
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'Ns' (model: 'advancedrocketry:models/block/models/topTank.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJModel: A color has already been defined for material 'None' in 'advancedrocketry:models/block/models/topTank.mtl'. The color defined by key 'Ks' will not be applied!
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'illum' (model: 'advancedrocketry:models/block/models/topTank.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'Ns' (model: 'advancedrocketry:models/block/models/bottomTank.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJModel: A color has already been defined for material 'None' in 'advancedrocketry:models/block/models/bottomTank.mtl'. The color defined by key 'Ks' will not be applied!
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'illum' (model: 'advancedrocketry:models/block/models/bottomTank.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'Ns' (model: 'advancedrocketry:models/block/models/middleTank.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJModel: A color has already been defined for material 'None' in 'advancedrocketry:models/block/models/middleTank.mtl'. The color defined by key 'Ks' will not be applied!
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'illum' (model: 'advancedrocketry:models/block/models/middleTank.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'Ns' (model: 'advancedrocketry:models/block/models/motor.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJModel: A color has already been defined for material 'Material' in 'advancedrocketry:models/block/models/motor.mtl'. The color defined by key 'Ks' will not be applied!
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'Ke' (model: 'advancedrocketry:models/block/models/motor.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'Ni' (model: 'advancedrocketry:models/block/models/motor.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'illum' (model: 'advancedrocketry:models/block/models/motor.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'Ns' (model: 'advancedrocketry:models/block/models/sawBlade.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJModel: A color has already been defined for material 'Material' in 'advancedrocketry:models/block/models/sawBlade.mtl'. The color defined by key 'Ks' will not be applied!
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'Ke' (model: 'advancedrocketry:models/block/models/sawBlade.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'Ni' (model: 'advancedrocketry:models/block/models/sawBlade.mtl') is not currently supported, skipping
[03:51:08] [Client thread/INFO]: OBJLoader.MaterialLibrary: key 'illum' (model: 'advancedrocketry:models/block/models/sawBlade.mtl') is not currently supported, skipping
[03:51:08] [Sound Library Loader/INFO]: Sound engine started
[03:51:09] [Client thread/INFO]: Max texture size: 16384
[03:51:09] [Client thread/INFO]: Created: 16x16 textures-atlas
[03:51:10] [Client thread/INFO]: Injecting itemstacks
[03:51:10] [Client thread/INFO]: Itemstack injection complete
[03:51:10] [Client thread/INFO]: Start registering sealable blocks
[03:51:10] [Client thread/INFO]: End registering sealable blocks
[03:51:10] [Client thread/INFO]: Start registering torch blocks
[03:51:10] [Client thread/INFO]: End registering torch blocks
[03:51:10] [Client thread/INFO]: Start registering Harvestable Gasses
[03:51:10] [Client thread/INFO]: End registering Harvestable Gasses
[03:51:10] [Client thread/INFO]: Start registering entity atmosphere bypass
[03:51:10] [Client thread/INFO]: End registering entity atmosphere bypass
[03:51:10] [Client thread/INFO]: Forge Mod Loader has successfully loaded 6 mods
[03:51:10] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Advanced Rocketry, FMLFileResourcePack:libVulpes
[03:51:11] [Client thread/INFO]: SoundSystem shutting down...
[03:51:11] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[03:51:11] [Sound Library Loader/INFO]: Starting up SoundSystem...
[03:51:11] [Thread-10/INFO]: Initializing LWJGL OpenAL
[03:51:11] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[03:51:11] [Thread-10/INFO]: OpenAL initialized.
[03:51:11] [Sound Library Loader/INFO]: Sound engine started
[03:51:12] [Client thread/INFO]: Max texture size: 16384
[03:51:12] [Client thread/WARN]: Texture advancedrocketry:textures/items/sawBladeAssembly.png with size 274x274 will have visual artifacts at mip level 4, it can only support level 1. Please report to the mod author that the texture should be some multiple of 16x16.
[03:51:12] [Client thread/WARN]: Texture advancedrocketry:textures/items/motor.png with size 278x278 will have visual artifacts at mip level 4, it can only support level 1. Please report to the mod author that the texture should be some multiple of 16x16.
[03:51:12] [Client thread/WARN]: Texture advancedrocketry:textures/blocks/clear.png with size 1x1 will have visual artifacts at mip level 4, it can only support level 0. Please report to the mod author that the texture should be some multiple of 16x16.
[03:51:12] [Client thread/INFO]: Created: 1024x512 textures-atlas
[03:51:14] [Client thread/WARN]: Skipping bad option: lastServer:
[03:51:19] [Client thread/INFO]: Stopping!
[03:51:19] [Client thread/INFO]: SoundSystem shutting down...
[03:51:19] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
`
here are some screenshots of the rolling machine and my Latest log. The only log in the folder. Configs are left the same as gened. 
forge-12.18.3.2254
AdvancedRocketry-1.10.2-1.0.13.jar
Libvulpes-1.10.2-0.1.16-universal.jar
Windows 10 64 bit
16GB total Ram
8 Dedicated to Minecraft
No other mods installed. 

Need anything else let me know

**Comment by zmaster587** [comment]
At least from what I gather from the screenshot, it looks like the control
block is not facing the right way, in the 2nd screenshot the side of the
block with the control panel-like texture should be facing you.  Could the
other machines be having the same problem?

**Comment by zmaster587** [comment]
Second to last screenshot*, sorry.

**Comment by NPCKiller** [comment]
Ill change the rotation when I get off work and Let you know.

**Comment by Jmon41** [comment]
Having the same issue but with the Crystallizer am using the 1.7.10-1.1.1 I tried rotating it and amongst other things. 
![2017-03-14_01 15 40](https://cloud.githubusercontent.com/assets/2856110/23886769/e8170f20-0853-11e7-8190-e5813694b765.png)
![2017-03-14_01 15 11](https://cloud.githubusercontent.com/assets/2856110/23886770/e819c1ac-0853-11e7-80e8-65dc49ff4781.png)
![2017-03-14_01 15 29](https://cloud.githubusercontent.com/assets/2856110/23886771/e81a1526-0853-11e7-97ca-0f93ad7f5663.png)
My game only has LibVulpes-1.7.10-0.2.0-universal and Advanced Rocketry 1.7.10-1.1.1

**Comment by zmaster587** [comment]
I think the input and output hatches might be reversed.  Though I think I
need to switch them because having the output on the left is weird

**Comment by Jmon41** [comment]
The recipe from the holographic Projector is telling me only one coil needs to be placed and the rf input needs to be on the opposite side. Even though in the projector it says it needs two coils.

**Comment by zmaster587** [comment]
I'll look at it on a sec, need to boot my computer

**Comment by zmaster587** [comment]
![image](https://cloud.githubusercontent.com/assets/3536685/23887835/8eaead24-085a-11e7-993a-88084384c2b8.png)
I'm seeing 2 coils in mine, also tested and build with the two coils (img right) and it worked for me

**Comment by zmaster587** [comment]
I screwed up one of the lines in the multiblock definition

**Comment by NPCKiller** [comment]
Sorry for the late reply I have been away. But I tested and that seems to be the case that it was facing the wrong way. Thanks for pointing it out. I have never had a mod do that.

**Comment by zmaster587** [comment]
Is everything good then?

**Comment by NPCKiller** [comment]
Look like it Ill post anything think else I find. Thank you very much for your time.
