### ISSUE TITLE
The server crashes when the satellite chip is placed in the terminal

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#469]
The server drops when the satellite chip is placed in the terminal, if the chip is incorrect. The terminal is trying to get the data anyway, although stack == null.

Stacktrace:

[Server thread/WARN]: Found initialization crash, stacktrace: java.lang.NullPointerException
java.lang.NullPointerException
 at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_111]
 at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:1.8.0_111]
 at net.minecraft.nbt.NBTTagCompound.func_74764_b(NBTTagCompound.java:136) ~[dh.class:?]
 at zmaster587.advancedRocketry.item.ItemSatelliteIdentificationChip.getSatellite(ItemSatelliteIdentificationChip.java:49) ~[ItemSatelliteIdentificationChip.class:?]
 at zmaster587.advancedRocketry.tile.Satellite.TileEntitySatelliteControlCenter.getSatelliteFromSlot(TileEntitySatelliteControlCenter.java:151) ~[TileEntitySatelliteControlCenter.class:?]
 at zmaster587.advancedRocketry.tile.Satellite.TileEntitySatelliteControlCenter.canPerformFunction(TileEntitySatelliteControlCenter.java:69) ~[TileEntitySatelliteControlCenter.class:?]
 at zmaster587.libVulpes.tile.TileEntityRFConsumer.func_145845_h(TileEntityRFConsumer.java:61) ~[TileEntityRFConsumer.class:unspecified]
 at zmaster587.advancedRocketry.tile.Satellite.TileEntitySatelliteControlCenter.func_145845_h(TileEntitySatelliteControlCenter.java:95) ~[TileEntitySatelliteControlCenter.class:?]
 at net.minecraft.world.World.func_72939_s(World.java:2546) [ahb.class:?]
 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:671) [mt.class:?]
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:958) [MinecraftServer.class:?]
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:812) [MinecraftServer.class:?]
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
![2017-03-26_11 00 41](https://cloud.githubusercontent.com/assets/3863970/24329937/378c984e-122d-11e7-884d-1a462dbb0121.png)

**Comment by zmaster587** [comment]
It doesn't look like the stack is null, otherwise that line of code would be impossible to hit.  What it looks like is happening is that it's trying to do a lookup of the String null in a concurrent hash map.  I'm not even sure why that segment of code is there to be honest, as it doesn't actually do anything.  I've removed the check so it should also fix the crash.

**Comment by denwd** [comment]
thanks)

**Comment by zmaster587** [comment]
no problem!
