### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#475]
Good day, crashes the server.
crash-reports

Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at zmaster587.advancedRocketry.cable.HandlerDataNetwork.tickAllNetworks(HandlerDataNetwork.java:20)
	at zmaster587.advancedRocketry.event.CableTickHandler.onTick(CableTickHandler.java:24)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_142_CableTickHandler_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zmaster587** [comment]
Is this with 1.0.9 or later?

**Comment by denwd** [comment]
Version compiled from the latest source.

**Comment by zmaster587** [comment]
Which branch?

**Comment by denwd** [comment]
master

**Comment by denwd** [comment]
the magazine weighs more than 1000 megabytes due to flooding

**Comment by zmaster587** [comment]
Is this also with thermos, and if so does it also occur with forge?  Also
was a cable placed or broken right before this occured and if so can you
provide information about the layout of that cable network?

**Comment by denwd** [comment]
Core Thermos
players do not say what they were doing during the crash
HashMap hanging 6 students, performed first CableTickHandler.onTick, then somewhere inside the tree another challenge comes with getting the iterator
therefore, this error

**Comment by denwd** [comment]
It is possible as that to correct or add the debugging?

**Comment by zmaster587** [comment]
I'm not entirely sure I understand, but if you're suggestin that another
handler is coming in and altering the list of cables.  I suspect it is very
unlikely because forge does all the updates on a single thread.

I think it's more likely that while updating one cable is removing either
itself or another cable from the list.

I'll look probably either Wednesday or Friday

**Comment by denwd** [comment]
Good, thanks
