### ISSUE TITLE
Crash of the server, error in api

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#476]
The server periodically crashes with such an error. Could not figure out which blocks are the cause.

[03:09:53] [Server thread/INFO]: Negative index in crash report handler (0/7)
[03:09:53] [Server thread/WARN]: Found initialization crash, stacktrace: java.lang.NullPointerException
java.lang.NullPointerException
[03:09:54] [Server thread/ERROR]: Exception caught during firing event zmaster587.advancedRocketry.api.RocketEvent$RocketLandedEvent@382c9c27:
java.lang.NullPointerException
[03:09:54] [Server thread/ERROR]: Index: 1 Listeners:
[03:09:54] [Server thread/ERROR]: 0: NORMAL
[03:09:54] [Server thread/ERROR]: 1: ASM: zmaster587.advancedRocketry.tile.station.TileLandingPad@2937eb8c onRocketLand(Lzmaster587/advancedRocketry/api/RocketEvent$RocketLandedEvent;)
[03:09:54] [Server thread/ERROR]: 2: ASM: zmaster587.advancedRocketry.tile.TileRocketBuilder@31fe2cce onRocketLand(Lzmaster587/advancedRocketry/api/RocketEvent$RocketLandedEvent;)

**Comment by zmaster587** [comment]
What version are you running/can you provide the full seever log?

**Comment by denwd** [comment]
Thermos-1.7.10-1614-server.jar

**Comment by denwd** [comment]
Server log more than 1 GB, I can not provide it. It mainly contains error repetitions.

**Comment by zmaster587** [comment]
Does this also occur with forge?  And can you provide a way to reliabily
replicate the issue?  Does it happen every time a rocket lands, only if a
rocket lands on a space station, only if it lands at a pad where
infrastructure is being automatically connected?

**Comment by denwd** [comment]
https://pastebin.com/bsJ42XuG    ((( log 2gb +
Do not know already what to do, the server keeps crashing((This happens when a person is moved from the station to the moon, onto a blank surface

**Comment by denwd** [comment]
An error occurs when the autopilot is operating, when the rocket touches the surface (any one) when landing. In this case, if the rocket sits on the orbital station, the rocket engines are not switched off. In addition, I noticed that if a player tries to create an orbital station on coordinates that are already occupied, then it is created on others.

In addition, if you break the blocks of the orbital station under the rocket, the rocket starts to fall down and an error appears:

[20:38:33 ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:234) [mn.class:?]
        at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:404) [EntityRegistry.class:1.7.10-0.test34.71]
        at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:62) [mn.class:?]
        at net.minecraft.world.WorldManager.func_72703_a(WorldManager.java:28) [mp.class:?]
        at net.minecraft.world.World.func_72923_a(World.java:1838) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1088) [mt.class:?]
        at net.minecraft.world.World.addEntity(World.java:1828) [ahb.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1719) [ahb.class:?]
        at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:1017) [oi.class:?]
        at zmaster587.advancedRocketry.entity.EntityRocket.travelToDimension(EntityRocket.java:922) [EntityRocket.class:?]
        at zmaster587.advancedRocketry.entity.EntityRocket.func_70071_h_(EntityRocket.java:537) [EntityRocket.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2680) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2632) [ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2441) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:671) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:958) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:812) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.IllegalStateException: Entity is already tracked! Entity: EntityRocket['Rocket'/41488, l='DIM-2', x=512,00, y=-0,07, z=-3584,00], Class: class zmaster587.advancedRocketry.entity.EntityRocket, ID: 41488
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:197) ~[mn.class:?]

**Comment by denwd** [comment]
UP)

**Comment by zmaster587** [comment]
Have you tried it with only Libvulpes, Advanced rocketry, and forge?

**Comment by denwd** [comment]
no, but I can try
