### ISSUE TITLE
An error occurred during the landing of a rocket

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#477]
This error happens when the rocket comes to the planet's surface during landing.

zmaster587.advancedRocketry.tile.station.TileLandingPad.onRocketLand(TileLandingPad.java:111)
 at cpw.mods.fml.common.eventhandler.ASMEventHandler_175_TileLandingPad_onRocketLand_RocketLandedEvent.invoke(.dynamic)
 at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
 at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
 at zmaster587.advancedRocketry.entity.EntityRocket.func_70071_h_(EntityRocket.java:512)
 at net.minecraft.world.World.func_72866_a(World.java:2744)
 at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877)
 at net.minecraft.world.World.func_72870_g(World.java:2682)

**Comment by denwd** [comment]
[2.txt](https://github.com/zmaster587/AdvancedRocketry/files/876682/2.txt)

**Comment by zmaster587** [comment]
Looks related to #476

**Comment by zmaster587** [comment]
does this also occur with only forge, advanced rocketry, and libvulpes?

**Comment by zmaster587** [comment]
I've added some debug output to shed some light on the issue as it really doesn't make sense to begin with.  I've put it into the master branch if you want to give it a shot.

**Comment by denwd** [comment]
Excellent thank you, I'll write when I get the data. You are a great developer)

**Comment by denwd** [comment]
I've reassembled and filled mod, waiting

**Comment by denwd** [comment]
This bug happens again, you can remove the debug
