### ISSUE TITLE
New crash server

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#484]
Description: Exception in server tick loop

java.lang.ClassCastException: zmaster587.libVulpes.items.ItemLinker cannot be cast to zmaster587.advancedRocketry.item.ItemAsteroidChip
        at zmaster587.advancedRocketry.mission.MissionOreMining.onMissionComplete(MissionOreMining.java:42)
        at zmaster587.advancedRocketry.mission.MissionResourceCollection.tickEntity(MissionResourceCollection.java:108)
        at zmaster587.advancedRocketry.dimension.DimensionProperties.tick(DimensionProperties.java:665)
        at zmaster587.advancedRocketry.dimension.DimensionManager.tickDimensions(DimensionManager.java:175)
        at zmaster587.advancedRocketry.event.PlanetEventHandler.tick(PlanetEventHandler.java:258)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_140_PlanetEventHandler_tick_ServerTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672)
        at java.lang.Thread.run(Thread.java:745)

https://pastebin.com/9s5dCbW6 server log

The server can no longer raise falls

Help(( the causes of the crash do not know(

**Comment by denwd** [comment]
[14:25:16 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 130ms
[14:25:17 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 176ms
[14:25:17 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 249ms
[14:25:18 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 456ms
[14:25:18 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 177ms
[14:25:18 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 204ms
[14:25:19 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 470ms
[14:25:19 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 361ms
[14:25:20 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 97ms
[14:25:20 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 223ms
[14:25:20 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 303ms
[14:25:21 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 75ms
[14:25:21 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 114ms
[14:25:21 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 140ms
[14:25:21 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 219ms
[14:25:22 WARN]: Possible lag source on unload TileEntity with GP: class zmaster587.libVulpes.tile.multiblock.hatch.TileInputHatch [-2](-1562, 125, 513) 72ms

**Comment by denwd** [comment]
Help(( the causes of the crash do not know(

**Comment by zmaster587** [comment]
It looks like it's caused by a rocket with a linker in the guidance
computer returning from a mining mission.  That's not supposed to be
possible but a fix is easy to implement.  I'll patch it when I can get to a
computer

**Comment by denwd** [comment]
Please fix, I can't start the server(

**Comment by zmaster587** [comment]
It's gonna be a few hours minimum, but you can open the
advRocketry/temp.Dat with an nbt editor and remove the mining mission with
the linker in the guidance computer and that should fix it

**Comment by denwd** [comment]
okay wait

**Comment by denwd** [comment]
thanks)
