### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#486]
An error occurs when the autopilot is operating, when the rocket touches the surface (any one) when landing. In this case, if the rocket sits on the orbital station, the rocket engines are not switched off. In addition, I noticed that if a player tries to create an orbital station on coordinates that are already occupied, then it is created on others.

https://pastebin.com/bsJ42XuG

In addition, if you break the blocks of the orbital station under the rocket, the rocket starts to fall down and an error appears:

[20:38:33 ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:234) [mn.class:?]
at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:404) [EntityRegistry.class:1.7.10-0.test34.71]
at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:62) [mn.class:?]
at net.minecraft.world.WorldManager.func_72703_a(WorldManager.java:28) [mp.class:?]
at net.minecraft.world.World.func_72923_a(World.java:1838) [ahb.class:?]
at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1088) [mt.class:?]
at net.minecraft.world.World.addEntity(World.java:1828) [ahb.class:?]
at net.minecraft.world.World.func_72838_d(World.java:1719) [ahb.class:?]
at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:1017) [oi.class:?]
at zmaster587.advancedRocketry.entity.EntityRocket.travelToDimension(EntityRocket.java:922) [EntityRocket.class:?]
at zmaster587.advancedRocketry.entity.EntityRocket.func_70071_h_(EntityRocket.java:537) [EntityRocket.class:?]
at net.minecraft.world.World.func_72866_a(World.java:2680) [ahb.class:?]
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [mt.class:?]
at net.minecraft.world.World.func_72870_g(World.java:2632) [ahb.class:?]
at net.minecraft.world.World.func_72939_s(World.java:2441) [ahb.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:671) [mt.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:958) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:812) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.IllegalStateException: Entity is already tracked! Entity: EntityRocket['Rocket'/41488, l='DIM-2', x=512,00, y=-0,07, z=-3584,00], Class: class zmaster587.advancedRocketry.entity.EntityRocket, ID: 41488
at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:197) ~[mn.class:?]

**Comment by denwd** [comment]
The rocket and the Shuttle gets to the end, and when you restart or warp they are duplicated((
![2017-03-31_11 51 04](https://cloud.githubusercontent.com/assets/3863970/24540358/472ce96a-160c-11e7-9fe8-be111da42b31.png)
![2017-03-31_11 58 54](https://cloud.githubusercontent.com/assets/3863970/24540366/562dfcce-160c-11e7-99ef-771ec30f1743.png)
![i956 cimgpsh_orig](https://cloud.githubusercontent.com/assets/3863970/24540403/886a0a3e-160c-11e7-8097-0280f98041eb.png)

**Comment by zmaster587** [comment]
I am fairly sure this is related to the first issue you posted, if the landing event does not fire weird things will happen.

2 things: warping only changes the skybox so it cannot have an effect on rocket behavior as it is a change in graphics which only occurs on the client, server updates  number indicating to dimenion the station's in orbit around, no blocks are moved, entities remain unchanged, etc, so it cannot possibly have an effect.

Second: does this also occur with only forge, advanced rocketry, and libvulpes?

**Comment by zmaster587** [comment]
related to #482, #477, #476,

**Comment by denwd** [comment]
I tried to make the error I did not, it appears the players randomly
