### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#525]
I launched 3 gas mining ships at the same time someone was doing his first launch to Sol 3. I was on my ship with one other person and I had a chicken with us that had a name tag on it.

Stacktrace:
	at zmaster587.libVulpes.util.AdjacencyGraph.findPathToBlock(AdjacencyGraph.java:129)
	at zmaster587.libVulpes.util.AdjacencyGraph.doesPathExist(AdjacencyGraph.java:154)
	at zmaster587.advancedRocketry.util.AtmosphereBlob.removeBlock(AtmosphereBlob.java:60)
	at zmaster587.advancedRocketry.atmosphere.AtmosphereHandler.onBlockChange(AtmosphereHandler.java:177)
	at net.minecraft.world.World.func_180501_a(World.java:351)
	at net.minecraft.world.World.func_175656_a(World.java:408)
	at zmaster587.advancedRocketry.tile.TileForceFieldProjector.func_73660_a(TileForceFieldProjector.java:46)

**Comment by zmaster587** [comment]
And the crash occurs in the atmosphere handler which should not be related to either of those things somehow.  Not entirely sure but there may be a concurrency issue going on here.  (Is this a concurrent modification exception or a nullpointer exception?)  Also are you using 1 or 3 for atmosphere threading calculation?

**Comment by Tyrantin** [comment]
3 on the AT. and as far as the Stack Trace, that is just 1 of the 43 that had repeated in the file.

**Comment by zmaster587** [comment]
There should be something like "java.lang.NullPointerException" or "java.util.ConcurrentModificationException" as the first line in the stact trace which specifies what type of error occured.  Because of the location it the code it could be one of several types each of which needs a different type of fix and has a different cause.
