### ISSUE TITLE
Unknown crash servers

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#545]
I don't know how to repeat it(

[08:03:40] [Server thread/INFO]: Unloading dimension 2
[08:03:40] [Server thread/WARN]: ****************************************
[08:03:40] [Server thread/WARN]: * Operation "remove" cause:

java.lang.Throwable
	at zmaster587.advancedRocketry.cable.HandlerDataNetwork.getNewNetworkID(HandlerDataNetwork.java:20)
	at zmaster587.advancedRocketry.tile.cables.TilePipe.onNeighborTileChange(TilePipe.java:182)
	at zmaster587.advancedRocketry.block.cable.BlockPipe.onNeighborChange(BlockPipe.java:70)
	at mekanism.common.util.MekanismUtils.notifyLoadedNeighborsOfTileChange(MekanismUtils.java:796)
	at mekanism.common.multipart.PartSidedPipe.notifyTileChange(PartSidedPipe.java:871)
	at mekanism.common.multipart.PartSidedPipe.onChunkLoad(PartSidedPipe.java:694)
	at codechicken.multipart.TileMultipart$$anonfun$onChunkLoad$1.apply(TileMultipart.scala:92)
	at codechicken.multipart.TileMultipart$$anonfun$onChunkLoad$1.apply(TileMultipart.scala:92)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76)
	at codechicken.multipart.TileMultipart.onChunkLoad(TileMultipart.scala:92)
	at codechicken.lib.world.TileChunkLoadHook.onChunkLoad(TileChunkLoadHook.java:26)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_169_TileChunkLoadHook_onChunkLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:1022)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:170)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:142)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:268)
	at net.minecraft.world.World.func_72964_e(World.java:756)
	at net.minecraft.world.World.func_147438_o(World.java:3147)
	at zmaster587.advancedRocketry.satellite.SatelliteData.performAction(SatelliteData.java:63)
	at zmaster587.advancedRocketry.tile.Satellite.TileEntitySatelliteControlCenter.extractData(TileEntitySatelliteControlCenter.java:250)
	at zmaster587.advancedRocketry.cable.DataNetwork.tick(DataNetwork.java:72)
	at zmaster587.advancedRocketry.cable.HandlerDataNetwork.tickAllNetworks(HandlerDataNetwork.java:39)
	at zmaster587.advancedRocketry.event.CableTickHandler.onTick(CableTickHandler.java:24)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_147_CableTickHandler_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672)
	at java.lang.Thread.run(Thread.java:745)

[08:03:40] [Server thread/WARN]: *  at zmaster587.advancedRocketry.cable.HandlerDataNetwork.tickAllNetworks(HandlerDataNetwork.java:43)
[08:03:40] [Server thread/WARN]: *  at zmaster587.advancedRocketry.event.CableTickHandler.onTick(CableTickHandler.java:24)
[08:03:40] [Server thread/WARN]: *  at cpw.mods.fml.common.eventhandler.ASMEventHandler_147_CableTickHandler_onTick_ServerTickEvent.invoke(.dynamic)
[08:03:40] [Server thread/WARN]: *  at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[08:03:40] [Server thread/WARN]: *  at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[08:03:40] [Server thread/WARN]: *  at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)...
[08:03:40] [Server thread/WARN]: ****************************************
[08:03:40] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ServerTickEvent@680d4a4b:
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_72-internal]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463) ~[?:1.8.0_72-internal]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461) ~[?:1.8.0_72-internal]
	at zmaster587.advancedRocketry.cable.HandlerDataNetwork.tickAllNetworks(HandlerDataNetwork.java:34) ~[HandlerDataNetwork.class:?]
	at zmaster587.advancedRocketry.event.CableTickHandler.onTick(CableTickHandler.java:24) ~[CableTickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_147_CableTickHandler_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251) [FMLCommonHandler.class:1.7.10-0.test34.71]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
[08:03:40] [Server thread/ERROR]: Index: 6 Listeners:
[08:03:40] [Server thread/ERROR]: 0: NORMAL
[08:03:40] [Server thread/ERROR]: 1: ASM: team.chisel.item.chisel.ChiselController@3beec235 openQueuedGui(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[08:03:40] [Server thread/ERROR]: 2: ASM: mods.immibis.core.MainThreadTaskQueue@2f29711a tickEventServer(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[08:03:40] [Server thread/ERROR]: 3: ASM: zmaster587.libVulpes.LibVulpes@478f48a5 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[08:03:40] [Server thread/ERROR]: 4: ASM: Network Registry:
[] onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[08:03:40] [Server thread/ERROR]: 5: ASM: zmaster587.advancedRocketry.event.PlanetEventHandler@265d33f6 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[08:03:40] [Server thread/ERROR]: 6: ASM: zmaster587.advancedRocketry.event.CableTickHandler@4bd70139 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[08:03:40] [Server thread/ERROR]: 7: ASM: zmaster587.advancedRocketry.stations.SpaceObjectManager@36693264 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[08:03:40] [Server thread/ERROR]: 8: ASM: codechicken.multipart.handler.MultipartEventHandler$@4987f510 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[08:03:40] [Server thread/ERROR]: 9: ASM: mods.immibis.core.commands.TPSCommand$TickHandler@23184ea9 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[08:03:40] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_72-internal]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463) ~[?:1.8.0_72-internal]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461) ~[?:1.8.0_72-internal]
	at zmaster587.advancedRocketry.cable.HandlerDataNetwork.tickAllNetworks(HandlerDataNetwork.java:34) ~[HandlerDataNetwork.class:?]
	at zmaster587.advancedRocketry.event.CableTickHandler.onTick(CableTickHandler.java:24) ~[CableTickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_147_CableTickHandler_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251) ~[FMLCommonHandler.class:1.7.10-0.test34.71]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
[08:03:40] [Server thread/ERROR]: This crash report has been saved to: /server/./crash-reports/crash-2017-04-10_08.03.40-server.txt
[08:03:40] [Server thread/INFO]: Stopping server

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10.04.17 8:03
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at zmaster587.advancedRocketry.cable.HandlerDataNetwork.tickAllNetworks(HandlerDataNetwork.java:34)
	at zmaster587.advancedRocketry.event.CableTickHandler.onTick(CableTickHandler.java:24)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_147_CableTickHandler_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zmaster587** [comment]
Without a way to reliably repeat is I've got no idea what can be causing this.

**Comment by denwd** [comment]
I can't find how players drop the server, you can add debugging what?
server log  https://pastebin.com/eUwYTG3B
------------------------------------------------------------------------------
crash-2017-05-03_20.19.08-server.txt
---- Minecraft Crash Report ----
// Java...

Time: 03.05.17 20:19
Description: Exception in server tick loop

java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
        at zmaster587.advancedRocketry.cable.HandlerDataNetwork.tickAllNetworks(HandlerDataNetwork.java:34)
        at zmaster587.advancedRocketry.event.CableTickHandler.onTick(CableTickHandler.java:24)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_147_CableTickHandler_onTick_ServerTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672)
        at java.lang.Thread.run(Thread.java:745)

**Comment by zmaster587** [comment]
I don't understand what you're asking?  Also does this continue to occur without mods other than advanced rocketry and libvulpes installed?
