### ISSUE TITLE
The player can not enter the server after an error

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#558]
[04:04:46] [Server thread/INFO]: user[/90.158.20.133:56051] logged in with entity id 139 at ([advRocketry/DIM41] -3617.4945842247757, 64.92999997735023, 4610.277433838582)
[04:04:46] [Server thread/ERROR]: HandshakeCompletionHandler exception
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:227) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:175) ~[ms.class:?]
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:408) ~[mr.class:?]
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:121) ~[mq.class:?]
	at net.minecraft.server.management.PlayerManager.func_72683_a(PlayerManager.java:176) ~[mq.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:299) ~[oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:381) ~[oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:219) ~[oi.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) ~[NetworkDispatcher.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:465) ~[NetworkDispatcher.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21) ~[HandshakeCompletionHandler.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:1.7.10-0.test34.71]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-0.test34.71]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:995) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:812) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at zmaster587.advancedRocketry.world.decoration.MapGenCrater.func_151538_a(MapGenCrater.java:60) ~[MapGenCrater.class:?]
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30) ~[aqx.class:?]
	at zmaster587.advancedRocketry.world.ChunkProviderPlanet.func_73154_d(ChunkProviderPlanet.java:276) ~[ChunkProviderPlanet.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:218) ~[ms.class:?]
	... 28 more
[04:04:46] [Server thread/ERROR]: There was a critical exception handling a packet on channel FML
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:227) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:175) ~[ms.class:?]
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:408) ~[mr.class:?]
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:121) ~[mq.class:?]
	at net.minecraft.server.management.PlayerManager.func_72683_a(PlayerManager.java:176) ~[mq.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:299) ~[oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:381) ~[oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:219) ~[oi.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) ~[NetworkDispatcher.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:465) ~[NetworkDispatcher.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21) ~[HandshakeCompletionHandler.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:1.7.10-0.test34.71]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-0.test34.71]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:995) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:812) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at zmaster587.advancedRocketry.world.decoration.MapGenCrater.func_151538_a(MapGenCrater.java:60) ~[MapGenCrater.class:?]
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30) ~[aqx.class:?]
	at zmaster587.advancedRocketry.world.ChunkProviderPlanet.func_73154_d(ChunkProviderPlanet.java:276) ~[ChunkProviderPlanet.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:218) ~[ms.class:?]
	... 28 more
[04:04:46] [Server thread/WARN]: Failed to handle packet for /91.237.27.144:56051
java.lang.NullPointerException
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101) ~[FMLProxyPacket.class:1.7.10-0.test34.71]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:995) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:812) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
[04:04:46] [Server thread/INFO]: user lost connection: Internal server error
[04:04:47] [Server thread/INFO]: Unloading dimension 41
[04:04:52] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[04:05:00] [User Authenticator #2/INFO]: UUID of player user is e0b324a2-3104-69b3-d531-ac26c65478e7
[04:05:00] [Netty IO #0/INFO]: Client protocol version 2

[04:05:00] [Server thread/INFO]: [Server thread] Server side modded connection established
[04:05:00] [Server thread/INFO]: Loading dimension 41 (advRocketry/DIM41) (net.minecraft.server.dedicated.DedicatedServer@3dc4f92f)
[04:05:00] [Server thread/INFO]: [RTG-INFO] World Seed: 2132626390202480712
[04:05:00] [Server thread/INFO]: user[/91.237.27.144:58898] logged in with entity id 152 at ([advRocketry/DIM41] -3617.4945842247757, 64.92999997735023, 4610.277433838582)
[04:05:00] [Server thread/ERROR]: HandshakeCompletionHandler exception
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:227) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:175) ~[ms.class:?]
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:408) ~[mr.class:?]
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:121) ~[mq.class:?]
	at net.minecraft.server.management.PlayerManager.func_72683_a(PlayerManager.java:176) ~[mq.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:299) ~[oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:381) ~[oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:219) ~[oi.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) ~[NetworkDispatcher.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:465) ~[NetworkDispatcher.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21) ~[HandshakeCompletionHandler.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:1.7.10-0.test34.71]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-0.test34.71]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:995) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:812) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at zmaster587.advancedRocketry.world.decoration.MapGenCrater.func_151538_a(MapGenCrater.java:60) ~[MapGenCrater.class:?]
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30) ~[aqx.class:?]
	at zmaster587.advancedRocketry.world.ChunkProviderPlanet.func_73154_d(ChunkProviderPlanet.java:276) ~[ChunkProviderPlanet.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:218) ~[ms.class:?]
	... 28 more
[04:05:00] [Server thread/ERROR]: There was a critical exception handling a packet on channel FML
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:227) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:175) ~[ms.class:?]
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:408) ~[mr.class:?]
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:121) ~[mq.class:?]
	at net.minecraft.server.management.PlayerManager.func_72683_a(PlayerManager.java:176) ~[mq.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:299) ~[oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:381) ~[oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:219) ~[oi.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) ~[NetworkDispatcher.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:465) ~[NetworkDispatcher.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21) ~[HandshakeCompletionHandler.class:1.7.10-0.test34.71]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:1.7.10-0.test34.71]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-0.test34.71]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:995) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:812) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at zmaster587.advancedRocketry.world.decoration.MapGenCrater.func_151538_a(MapGenCrater.java:60) ~[MapGenCrater.class:?]
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30) ~[aqx.class:?]
	at zmaster587.advancedRocketry.world.ChunkProviderPlanet.func_73154_d(ChunkProviderPlanet.java:276) ~[ChunkProviderPlanet.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:218) ~[ms.class:?]
	... 28 more
[04:05:00] [Server thread/WARN]: Failed to handle packet for /91.237.27.144:58898
java.lang.NullPointerException
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101) ~[FMLProxyPacket.class:1.7.10-0.test34.71]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:995) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:812) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
[04:05:00] [Server thread/INFO]: user lost connection: Internal server error
[04:05:01] [Server thread/INFO]: Unloading dimension 41

**Comment by denwd** [comment]
At the same time the player throws from a server and not let back, showing the error "Internal Server Error". Check, please, the generation of craters.

**Comment by denwd** [comment]
I deleted biome the marsh in the troubled world in temp.dat. The error has disappeared. The problem is in this biome.

**Comment by zmaster587** [comment]
looks related to #529
