### ISSUE TITLE
Fluids that does not have a block and a default container cannot be used in customized recipes

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#590]
Such fluids are not shown in NEI recipes
I think it's related to https://github.com/zmaster587/AdvancedRocketry/issues/400

**Comment by zmaster587** [comment]
Likely.  Also can you check to see if the recipe actually uses the liquid even though NEI is not displaying it?  My theory is that because I convert to a block/item for NEI even though the internal recipe uses fluidstacks that it's just a visual issue.

**Comment by zmaster587** [comment]
Can you try one of these builds and let me know if it's fixed, also #400?
1.1.x series http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/RoundPlanets7_10/7/
1.0.x series http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/master/9/

**Comment by wormzjl** [comment]
The problem is not solved, however I can confirm this problem is only visual

**Comment by wormzjl** [comment]
Also with the version provided, I was kicked out of the game with this error in the log while trying to use the holo projector 
[19:43:24] [Server thread/ERROR]: There was a critical exception handling a packet on channel libVulpes
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source) ~[?:1.8.0_121]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_121]
	at zmaster587.libVulpes.items.ItemProjector.useNetworkData(ItemProjector.java:511) ~[ItemProjector.class:unspecified]
	at zmaster587.libVulpes.network.PacketItemModifcation.execute(PacketItemModifcation.java:118) ~[PacketItemModifcation.class:unspecified]
	at zmaster587.libVulpes.network.PacketItemModifcation.executeServer(PacketItemModifcation.java:128) ~[PacketItemModifcation.class:unspecified]
	at zmaster587.libVulpes.network.PacketHandler$HandlerServer.channelRead0(PacketHandler.java:151) ~[PacketHandler$HandlerServer.class:unspecified]
	at zmaster587.libVulpes.network.PacketHandler$HandlerServer.channelRead0(PacketHandler.java:139) ~[PacketHandler$HandlerServer.class:unspecified]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
	at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by zmaster587** [comment]
What about this build?
stable: http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/master/10/
alpha: http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/RoundPlanets7_10/9/
libvulpes for alpha build only: http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/unstable1_7/6/

**Comment by wormzjl** [comment]
Nope...I think it's probably better to make the author of the other mod make a fluid block
However I got this
![image](https://cloud.githubusercontent.com/assets/2989009/25497614/7e74727e-2b85-11e7-98f7-959cf70c406b.png)
![image](https://cloud.githubusercontent.com/assets/2989009/25497620/82decd78-2b85-11e7-9e02-1c9e816e540b.png)

**Comment by zmaster587** [comment]
Odd... I tested that last build with a fluid with no fluid block and it
worked fine.

Can you get me the name of the mod and fluid?

I'll look into the texture issue... idk what happened there... maybe the
build sever screwed up or something.

**Comment by wormzjl** [comment]
https://forum.industrial-craft.net/thread/10458-ic2-exp-1-7-10-v0-633-ihl-tools-machines/?pageNo=1
this mod, with ammonia fluid

**Comment by zmaster587** [comment]
![image](https://cloud.githubusercontent.com/assets/3536685/25510149/f4b26224-2b8b-11e7-9339-244f3e9380cf.png)
Using the recipe

	<Recipe timeRequired="100" power ="20">
		<input>
			<fluidStack>ammonia 10</fluidStack>
		</input>
		<output>
			<fluidStack>oxygen 100</fluidStack>
			<fluidStack>hydrogen 100</fluidStack>
		</output>
	</Recipe>

in the electolyser.xml yields the above image.  Is it just empty for you?

**Comment by wormzjl** [comment]
![image](https://cloud.githubusercontent.com/assets/2989009/25517265/dc8d9976-2bee-11e7-8bae-ae20866b12dd.png)
It's like this for me

**Comment by zmaster587** [comment]
That is indeed strange.  Using R or U seems to work on AR's containers.  I'll have a look into that and see if i can find why IC2's isn't working as expected

**Comment by zmaster587** [comment]
Stranger and stranger.  If you hit R on the hydrogen cell from IHL tools I am presented with the recipe for water => H2 + O2.  However with IC2's universal fluid cell version of hydrogen I am not.  So it appears to be something specific to the way IC2 is doing it.

**Comment by zmaster587** [comment]
Would you be able to give it a shot with this version?

Alpha Libvulpes:
http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/unstable1_7/7/

Alpha Advanced Rocketry (Note some experimental changes were done to planet XML loading/storage, so I would strongly advise backing up the world if you use this version)
http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/RoundPlanets7_10/10/


Stable:
http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/master/11/

**Comment by wormzjl** [comment]
Seems good, it works smoothly now :)

**Comment by zmaster587** [comment]
Alright! good!  What about issue #400?

**Comment by zmaster587** [comment]
Actually hurr durr it would have to be, fluid is not displayed as buckets anymore.

**Comment by wormzjl** [comment]
Yeah in the end they are the same issue, thx
