### ISSUE TITLE
AIOOB error visiting other planets

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#601]
[15:00:50] [Server thread/ERROR] [FML/]: HandshakeCompletionHandler exception
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:268) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217) ~[ms.class:?]
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:408) ~[mr.class:?]
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:121) ~[mq.class:?]
	at net.minecraft.server.management.PlayerManager.func_72683_a(PlayerManager.java:176) ~[mq.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:304) ~[oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:387) ~[oi.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:223) ~[oi.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:200) ~[NetworkDispatcher.class:1.7.10-1614.58]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:475) ~[NetworkDispatcher.class:1.7.10-1614.58]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21) ~[HandshakeCompletionHandler.class:1.7.10-1614.58]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:1.7.10-1614.58]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.58]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 65536
	at zmaster587.advancedRocketry.world.decoration.MapGenCrater.func_151538_a(MapGenCrater.java:53) ~[MapGenCrater.class:?]
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30) ~[aqx.class:?]
	at zmaster587.advancedRocketry.world.ChunkProviderPlanet.func_73154_d(ChunkProviderPlanet.java:276) ~[ChunkProviderPlanet.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:259) ~[ms.class:?]
	... 28 more

The full log can be found here, seems that the error happens when visiting DIM10
https://gist.githubusercontent.com/wormzjl/c0d1398b7fff4f3a6e5f19c0b8b9e8cd/raw/4fc4d7ea97aa5234d4b47a4e6d8fbd1d14f13bb6/gistfile1.txt

And my planet definition
https://gist.github.com/wormzjl/cd8fafae8b4519102d041105a39e4e7e

I'm using the version you have given me in this issue
https://github.com/zmaster587/AdvancedRocketry/issues/590

**Comment by zmaster587** [comment]
Did you change the default biomeid in the Advanced Rocketry config at all?  If so, what is biome id 92?

**Comment by wormzjl** [comment]
Nope

92 is Occupied by Hot Dry Rock (zmaster587.advancedRocketry.world.biome.BiomeGenHotDryRock)

**Comment by zmaster587** [comment]
What about with http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/RoundPlanets7_10/12/

or 

http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/master/12/

**Comment by wormzjl** [comment]
seems to be fixed, thanks!
