### ISSUE TITLE
Docking Pad Crash

### ISSUE THREAD

**Issue by EnderInvader** [zmaster587/AdvancedRocketry#648]
Whenever I place down a docking pad, my game crashes. Afterward, I can start up the game and still be able to get in the world. The docking pad itself works fine after I load the game.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.2.0b.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 5/21/17 12:32 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Empty string not allowed
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:128)
	at zmaster587.advancedRocketry.tile.station.TileLandingPad.func_189515_b(TileLandingPad.java:328)
	at zmaster587.advancedRocketry.tile.station.TileLandingPad.func_189518_D_(TileLandingPad.java:254)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:287)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:249)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:128)
	at zmaster587.advancedRocketry.tile.station.TileLandingPad.func_189515_b(TileLandingPad.java:328)
	at zmaster587.advancedRocketry.tile.station.TileLandingPad.func_189518_D_(TileLandingPad.java:254)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:287)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:249)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
	Level name: TOO SPACE
	All players: 1 total; [EntityPlayerMP['Ender_Invader'/79, l='TOO SPACE', x=769.77, y=53.46, z=413.47]]
	Chunk stats: ServerChunkCache: 289 Drop: 0
	Level seed: -8915353630289029347
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;minecraft:bedrock,50*minecraft:dirt,minecraft:grass;1;village
	Level spawn location: World: (776,4,392), Chunk: (at 8,0,8 in 48,24; contains blocks 768,0,384 to 783,255,399), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 362169 game time, 43193 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 3580 (now: false), thunder time: 141118 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 300633848 bytes (286 MB) / 680579072 bytes (649 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	libVulpes{0.2.3.} [libVulpes] (LibVulpes-1.10.2-0.2.3-universal.jar) 
	UCHIJAAAA	advancedRocketry{1.2.0b} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.2.0b.jar) 
	UCHIJAAAA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.2.0b.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Ender_Invader'/79, l='TOO SPACE', x=769.77, y=53.46, z=413.47]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by zmaster587** [comment]
Does this still occur in 1.2.0c?
