### ISSUE TITLE
server bug

### ISSUE THREAD

**Issue by Nidero** [zmaster587/AdvancedRocketry#666]
The use of the rocket on the server Click the select dst button will cause the player client to leave the line, this situation should only appear on the server. This is not crash, but it should be bug.

Mod version:
AdvancedRocketry-1.7.10-1.2.0
LibVulpes-1.7.10-0.2.3-universal

The server used is thermos

The following is the contents of logs:

[16:49:42] [Server thread/ERROR]: 
There was a critical exception handling a packet on channel libVulpes
java.lang.NoClassDefFoundError: zmaster587/libVulpes/inventory/modules/ModuleImage
	at zmaster587.advancedRocketry.entity.EntityRocket.getModules(EntityRocket.java:1370) ~[EntityRocket.class:?]
	at zmaster587.libVulpes.inventory.GuiHandler.getServerGuiElement(GuiHandler.java:40) ~[GuiHandler.class:unspecified]
	at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243) ~[NetworkRegistry.class:1.7.10-1614.58]
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:85) ~[FMLNetworkHandler.class:1.7.10-1614.58]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2437) ~[yz.class:?]
	at zmaster587.advancedRocketry.entity.EntityRocket.useNetworkData(EntityRocket.java:1193) ~[EntityRocket.class:?]
	at zmaster587.libVulpes.network.PacketEntity.execute(PacketEntity.java:106) ~[PacketEntity.class:unspecified]
	at zmaster587.libVulpes.network.PacketEntity.executeServer(PacketEntity.java:111) ~[PacketEntity.class:unspecified]
	at zmaster587.libVulpes.network.PacketHandler$HandlerServer.channelRead0(PacketHandler.java:151) ~[PacketHandler$HandlerServer.class:unspecified]
	at zmaster587.libVulpes.network.PacketHandler$HandlerServer.channelRead0(PacketHandler.java:139) ~[PacketHandler$HandlerServer.class:unspecified]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.58]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: zmaster587.libVulpes.inventory.modules.ModuleImage
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]

**Comment by zmaster587** [comment]
This should have been fixed in AdvancedRocketry-1.7.10-1.2.0b, can you try to replicate the issue with at least that version?
