### ISSUE TITLE
The use of the observatory in the thermos server causes the client to crash. 

### ISSUE THREAD

**Issue by Nidero** [zmaster587/AdvancedRocketry#674]
Everyone in the server is having this problem, including me.
May be with the server mod conflict, may be other problems, please help me find

This is the client's crash content：
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 17-6-2 下午2:40
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 9, Size: 9
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1062)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:120)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1062)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['qqwang'/209558086, l='MpServer', x=20007.87, y=84.62, z=20019.66]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (220,65,240), Chunk: (at 12,4,0 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 45642289 game time, 46678775 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 47 total; [EntityCow['牛'/128, l='MpServer', x=19977.50, y=73.00, z=19992.16], EntitySkeleton['骷髅'/209560317, l='MpServer', x=20027.66, y=87.00, z=19998.06], EntityCow['牛'/129, l='MpServer', x=19975.16, y=73.00, z=19992.50], EntitySpider['蜘蛛'/209508350, l='MpServer', x=20018.72, y=79.00, z=20002.75], EntityHauntedTool['Haunted Tool'/209560319, l='MpServer', x=20024.44, y=87.00, z=20011.66], EntityXPOrb['经验球'/209607543, l='MpServer', x=20018.78, y=77.19, z=20002.25], EntityBasalz['岩石人'/209607536, l='MpServer', x=20024.50, y=87.00, z=20002.50], EntitySpider['蜘蛛'/209534573, l='MpServer', x=20018.72, y=79.00, z=20004.28], EntityZombie['僵尸'/209534560, l='MpServer', x=20026.70, y=76.00, z=20004.73], EntityDMinion['Skull Minion'/209335013, l='MpServer', x=20018.59, y=80.00, z=20005.25], EntityCreeper['爬行者'/209533791, l='MpServer', x=20023.31, y=87.00, z=20011.09], Bandit['强盗'/209607764, l='MpServer', x=19997.50, y=6.00, z=19984.50], EntityAspectOrb['要素球'/209607502, l='MpServer', x=20019.41, y=76.00, z=20003.00], EntityAspectOrb['要素球'/209607503, l='MpServer', x=20019.06, y=77.06, z=20005.01], EntityAspectOrb['要素球'/209607500, l='MpServer', x=20019.42, y=76.00, z=20003.06], EntityAspectOrb['要素球'/209607501, l='MpServer', x=20016.94, y=76.06, z=20002.64], EntityPigZombie['僵尸猪人'/205957756, l='MpServer', x=20011.00, y=73.00, z=20011.56], EntityItem['item.item.snowball'/209136459, l='MpServer', x=19994.19, y=73.13, z=20008.59], EntitySpider['蜘蛛'/209532738, l='MpServer', x=20019.70, y=78.00, z=20004.26], EntityXPOrb['经验球'/209607489, l='MpServer', x=20015.56, y=76.25, z=20002.22], EntityClientPlayerMP['qqwang'/209558086, l='MpServer', x=20007.87, y=84.62, z=20019.66], EntityDMimic['Mimic Chest'/209263788, l='MpServer', x=20030.50, y=5.00, z=20004.50], EntityWitch['女巫'/209484714, l='MpServer', x=20023.03, y=78.00, z=20004.70], EntityWisp['精灵'/209583915, l='MpServer', x=20028.53, y=87.00, z=19993.50], EntitySkeleton['骷髅'/209559210, l='MpServer', x=20024.59, y=87.00, z=20014.56], EntitySpider['蜘蛛'/209583914, l='MpServer', x=20026.28, y=86.00, z=19999.54], EntitySkeleton['骷髅'/209607064, l='MpServer', x=20028.50, y=87.00, z=20008.31], EntitySpark['火花'/153472847, l='MpServer', x=20008.50, y=74.50, z=19979.50], EntityXPOrb['经验球'/209358865, l='MpServer', x=20015.41, y=76.25, z=20002.72], EntitySpark['火花'/153472846, l='MpServer', x=20008.50, y=74.50, z=19978.50], EntitySkeleton['骷髅'/209534224, l='MpServer', x=20020.80, y=78.00, z=20004.69], EntityItem['item.item.bone'/209534480, l='MpServer', x=20023.13, y=87.13, z=20011.22], EntitySpark['火花'/153472853, l='MpServer', x=20010.50, y=74.50, z=19978.50], EntitySpark['火花'/153472852, l='MpServer', x=20010.50, y=74.50, z=19977.50], EntitySpark['火花'/153472855, l='MpServer', x=20002.50, y=74.50, z=19974.50], EntitySpark['火花'/153472854, l='MpServer', x=20010.50, y=74.50, z=19979.50], EntitySpark['火花'/153472849, l='MpServer', x=20009.50, y=74.50, z=19978.50], EntityGolemBase['稻草傀儡'/373, l='MpServer', x=19996.50, y=75.88, z=19995.50], EntitySpark['火花'/153472848, l='MpServer', x=20009.50, y=74.50, z=19977.50], EntitySnowman['雪傀儡'/374, l='MpServer', x=19993.50, y=73.00, z=20009.50], EntitySpark['火花'/153472851, l='MpServer', x=20008.50, y=74.50, z=19977.50], EntitySpark['火花'/153472850, l='MpServer', x=20009.50, y=74.50, z=19979.50], EntitySpark['火花'/153472857, l='MpServer', x=20007.50, y=75.50, z=19972.50], EntitySpark['火花'/153472856, l='MpServer', x=20003.50, y=74.50, z=19972.50], EntityCreeper['爬行者'/209560320, l='MpServer', x=20019.79, y=78.00, z=20002.31], EntityCow['牛'/127, l='MpServer', x=19976.28, y=73.00, z=19992.97], EntityCreeper['爬行者'/209583874, l='MpServer', x=20022.74, y=78.00, z=20003.44]]
	Retry entities: 0 total; []
	Server brand: thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:120)

**Comment by zmaster587** [comment]
does this occur without thermos installed?  Also what version of the mod are you using and next time would it be possible to use pastebin.com for the crash report instead to keep things more organized?

**Comment by Janrupf** [comment]
This isn't related to thermos, it can also happen on a FTB-Server (not shure if they modded by the FTB Team).

**Comment by EasterncheesE** [comment]
Hello.
Minecraft 1.7.10, Forge 1614, Thermos (build 57).
Getting this crash for client on modded server. 
Conditions:

1) I had 1.019b version of the mod because it crashed. So i had observatory already installed (no motors, with glass, 1 data block). 
2) I upgraded it with best motor, lens instead of the glass and put 3 data blocks.
3) When try to use it, client get CTD.
Please see the pastebin log below. If any additional info needed, i will be glad to provide in order to fix this issue.
https://pastebin.com/y4m8u2dk
