### ISSUE TITLE
[1.10.2]Chrash after terraformer started to change biomes

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [zmaster587/AdvancedRocketry#678]
First there are massive lags (like if you are on an server with bad ping) and then it freezes and gives me this in the log:
[Edit]: This continues even after restarting

Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@1a6442e9:
java.lang.NullPointerException
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:511)
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator.next(Long2ObjectOpenHashMap.java:706)
	at zmaster587.advancedRocketry.event.PlanetEventHandler.serverTickEvent(PlanetEventHandler.java:389)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_40_PlanetEventHandler_serverTickEvent_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
	FML	Index: 1 Listeners:
	FML	0: NORMAL
	FML	1: ASM: zmaster587.advancedRocketry.event.PlanetEventHandler@39459b5a serverTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
	net.minecraft.server.MinecraftServer	Encountered an unexpected exception
java.lang.NullPointerException
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:511)
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator.next(Long2ObjectOpenHashMap.java:706)
	at zmaster587.advancedRocketry.event.PlanetEventHandler.serverTickEvent(PlanetEventHandler.java:389)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_40_PlanetEventHandler_serverTickEvent_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zmaster587** [comment]
Looks related to #579.

**Comment by ErdbeerbaerLP** [comment]
I alteady removed all mods and i only did 1 terraforming process

**Comment by zmaster587** [comment]
Alright, I'm working on trying to replicate the issue on my end currently

**Comment by zmaster587** [comment]
I've not been able to replicate the issue, I do get a burst of lag, but that settles down after 500ms or so and the game does not crash.  So I'm wondering if we're using a different version of fastutils or there's some implementation difference.  Best thing I can think of is to just try to catch the exception to at least prevent the game crashing and perhaps print some info on it.  I'll link a modified build of the mod in a few minutes.

**Comment by zmaster587** [comment]
http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/
http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/
If you could test with one of the latest builds here I'd greatly appriciate it.
The roundplanets builds are the line for the alpha builds on curse and the other builds are the stable builds.

**Comment by ErdbeerbaerLP** [comment]
There are 26 missing block/items in this world save
(ex. libvulpes:advancedMotor, advancedrocketry:gravityMachine, ...)

**Comment by zmaster587** [comment]
did you get the roundplanets AR build and unstable libvulpes build?

**Comment by ErdbeerbaerLP** [comment]
no both from the links (before i had the from curse)

**Comment by zmaster587** [comment]
Which build did you get from curse?

**Comment by ErdbeerbaerLP** [comment]
the newest alpha... wait i look which it is

**Comment by ErdbeerbaerLP** [comment]
AV 1.10.2-1.2.0c.jar
lib 1.10.2-0.2.3-universal.jar

**Comment by zmaster587** [comment]
Do these build yeild the same issue?

http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/RoundPlanets1_10/lastSuccessfulBuild/artifact/build/libs/AdvancedRocketry-1.10.2-1.2.1-25.jar

http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/unstable1_10/lastSuccessfulBuild/artifact/output/LibVulpes-1.10.2-0.2.4-16-universal.jar

**Comment by ErdbeerbaerLP** [comment]
the lags are there but no chrash right now

**Comment by ErdbeerbaerLP** [comment]
and my rocket is gone

**Comment by zmaster587** [comment]
that may have happened due to the initial crash, MC is weird about saving stuff sometimes when the game crashes

**Comment by ErdbeerbaerLP** [comment]
LOG: Can't keep up! Did the system time change, or is the server overloaded? Running 88077ms behind, skipping 1761 tick(s)

**Comment by ErdbeerbaerLP** [comment]
and what is the guidiance computer acces hatch? it was not in my inventory before

**Comment by zmaster587** [comment]
I know it will lag initially, I'm asking if the lag dimishishes after a few minutes.

The guidance computer access hatch is an upcoming infrastructure block that can be linked to rockets to allow players to insert/remove chips from rockets with other automation mods/hoppers

**Comment by ErdbeerbaerLP** [comment]
and the lag is still there... i let it run while i go outside with my dog (10-15mins)

**Comment by ErdbeerbaerLP** [comment]
small extra bug: the holographic planets are not removing after breaking the holo planet selector

**Comment by ErdbeerbaerLP** [comment]
it works but my terraformer is still at the same state... no progress


and the planets are now gone too... no bug

**Comment by zmaster587** [comment]
Is java running low on memory?  Other than that idk what else to say about the lag, I've been testing this on a laptop with a i5@2.4GHz from 2011 and on a core 2 duo@3.00GHz from 2009 and the only lag I come across is from the blue beams rendering, but those go away after a large area has already been terraformed

**Comment by zmaster587** [comment]
Can you send the advRocketry/planetdefs.xml file?

**Comment by ErdbeerbaerLP** [comment]
7.5gb / 8gb ram for minecraft

**Comment by ErdbeerbaerLP** [comment]
and the plaet file i already edited for an newer world

**Comment by zmaster587** [comment]
How much does your computer have total?

**Comment by ErdbeerbaerLP** [comment]
8 like i wrote

**Comment by zmaster587** [comment]
how much is allocated to java?

**Comment by ErdbeerbaerLP** [comment]
idk... but java is 64 bit jdk

**Comment by zmaster587** [comment]
if you hit f3 in minecraft what is the largest number on the first line on the top right

**Comment by ErdbeerbaerLP** [comment]
64 (from 64 bit)

**Comment by zmaster587** [comment]
sorry, second line, I'm used to 1.7.10's output

**Comment by ErdbeerbaerLP** [comment]
3674/7527MB

**Comment by ErdbeerbaerLP** [comment]
and my log is cleared lol

**Comment by zmaster587** [comment]
alright.  Two things you may want to consider, java will use much more RAM than you allocate to heap.  EX I currently have 984MB allocated to heap in java, but the java process itself is using 1.8GB of RAM on my system.  So you very easily could be exhausting system resources, you may want to dial it back to 4GB, and if that's too little, 4.5GB.  Also that's a large amount of memory in use for only libvulpes and AR, are you running with other mods as well?

**Comment by ErdbeerbaerLP** [comment]
jei currently but before there were more

**Comment by zmaster587** [comment]
Also, when I break the holo planet selector, the planets do go away.

Hmm... maybe garbage collection just hasn't been triggered yet then.  In that case there's no reason you'd need more than 2GB allocated to java

**Comment by ErdbeerbaerLP** [comment]
because i want more than 10fps

**Comment by ErdbeerbaerLP** [comment]
(no resource pack)

**Comment by zmaster587** [comment]
I'd like you to try a set of java args and see if this helps with your frame rate: 
-Xms128M -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M

**Comment by ErdbeerbaerLP** [comment]
how do i set special arguments in the curse launcher xD i only know how to change ram there

**Comment by zmaster587** [comment]
I'd have to look, the curse launcher does not support my platform, give me a sec

**Comment by zmaster587** [comment]
supposedly https://support.feed-the-beast.com/faq/assets/images/curseSettings/CurseUI_2016-11-11_15-08-22-javaArgs.png

**Comment by ErdbeerbaerLP** [comment]
quit to title chrashes... no log now... and no new file in "chrash-reports"

**Comment by ErdbeerbaerLP** [comment]
lags removed completely

**Comment by ErdbeerbaerLP** [comment]
no chrash at quit

**Comment by zmaster587** [comment]
Should I take that as it launches, or was that a joke about it crashing on start?

**Comment by ErdbeerbaerLP** [comment]
no chrash at start it was while quitting the game to restart it with the new args

**Comment by zmaster587** [comment]
Can you give the terraformer another go and see if it works as expected this time?

**Comment by ErdbeerbaerLP** [comment]
it works

**Comment by zmaster587** [comment]
Alright, thanks for your help and fast replies and good luck.

**Comment by ErdbeerbaerLP** [comment]
back again.... the terraformer (0.30 pressure was the last i was able to see) just made mesa on grass biome and now the world is lagging again.... cant do anything exept walking around

**Comment by ErdbeerbaerLP** [comment]
quit--> chrash

**Comment by zmaster587** [comment]
can you upload the crash log?

**Comment by ErdbeerbaerLP** [comment]
if i would have it... in exact the time i exit the game my log clears and no file in chrash reports is created

**Comment by zmaster587** [comment]
The crash report should be both saved as it's own file in the crash reports folder in the game directory, and in the fml-client-latest.log file when the game exits.  So even if the log is cleared there are two other locations you can find it.

**Comment by ErdbeerbaerLP** [comment]
chrash report is no new file....

the last lines of the log file:
[20:46:59] [Server thread/WARN]: Keeping entity Pig that already exists with UUID ba741133-a745-4f2b-ac91-0887bd01dcd5
[20:54:22] [Client thread/INFO]: [CHAT] Atmosphere Type: air @ 0.3 atm
[20:54:22] [Client thread/INFO]: [CHAT] Breathable: Yes
[20:55:43] [Server thread/INFO]: Saving and pausing game...
[20:55:43] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[20:55:43] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[20:55:43] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[20:55:43] [Server thread/INFO]: Saving chunks for level 'New World'/planet

**Comment by zmaster587** [comment]
are you sure that's fml-client-latest.log and not latest.log?

**Comment by ErdbeerbaerLP** [comment]
where is the other file there were only MANY zip(or zip like) files and latest.log

**Comment by zmaster587** [comment]
It may be packed into the most recent zip

**Comment by ErdbeerbaerLP** [comment]
that is older (where it was working without lags)

**Comment by zmaster587** [comment]
I think the zip files are one older than the current launch if you know what I mean, launching the game again should make the next most recent log appear and so on.  I suspect the currently log is still somewhere though.  You could also try opening your game directory in explorer, hitting ctrl+F and searching "fml-client-latest".  I've got no way of looking myself as my platform is not supported for the new version of the launcher and there's no documentation that I can find.

**Comment by ErdbeerbaerLP** [comment]
no there is not the file

**Comment by zmaster587** [comment]
https://i.imgur.com/RfdyNRK.png
Do you have "open output log when game starts" ticked as shown here?

**Comment by ErdbeerbaerLP** [comment]
yes and this log gets cleared
