### ISSUE TITLE
Massive spam on player login

### ISSUE THREAD

**Issue by CovertJaguar** [zmaster587/AdvancedRocketry#712]
Version LibVulpes-1.10.2-0.2.3/AdvancedRocketry-1.10.2-1.2.0c

```
[04:42:14] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.RuntimeException: DISPATCHER expects a NetworkDispatcher
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$2.validateArgs(FMLOutboundHandler.java:81) ~[FMLOutboundHandler$OutboundTarget$2.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:282) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[minecraft_server.1.10.2.jar:?]
	at zmaster587.libVulpes.network.PacketHandler.sendToDispatcher(PacketHandler.java:178) [PacketHandler.class:unspecified]
	at zmaster587.advancedRocketry.event.PlanetEventHandler.playerLoggedInEvent(PlanetEventHandler.java:267) [PlanetEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_723_PlanetEventHandler_playerLoggedInEvent_ServerConnectionFromClientEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:257) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by zmaster587** [comment]
I've not been able to replicate it on either my server or in single player.  Do you have other mods installed?  Also what version of forge?

**Comment by CovertJaguar** [comment]
MinecraftForge v12.18.3.2281

Mostly accurate modlist:
https://docs.google.com/spreadsheets/d/1AHxz1KdAVzV6CiEWW-atoDBGth7GeauheEf95J33YuY/edit#gid=0

**Comment by zmaster587** [comment]
Alright, thanks.  Looking into it.

**Comment by zmaster587** [comment]
I've tried connecting to a server using Forge 12.18.3.2281 and the following modlist ( https://pastebin.com/SugsZwjv ) and still not getting anything like the above log.  There were a few links where the site just timed out and I had some difficulty finding (anything on http://[subdomain].vex.tty.sh)

**Comment by CovertJaguar** [comment]
https://dl.dropboxusercontent.com/u/38558957/Minecraft/modpack-2017-06-15-1.22.zip

**Comment by Terpo** [comment]
I've got something very similiar for 1.11.2:
https://gist.github.com/Terpo/1a6550eaed290919e79eb7e8cb9bc7a3
This is the output I am getting when connecting to the server.

Modlist: https://gist.github.com/Terpo/2b0edfd02c1b711bc8cf6c78732375e6
LibVulpes-1.11.2-0.2.5-universal.jar
AdvancedRocketry-1.11.2-1.2.2.jar
Forge: 2315

**Comment by zmaster587** [comment]
@CovertJaguar does this occur on a new world?  I downloaded and ran the pack you sent and upon connecting to the server I still did not get any spam.
Log from server run:
[fml-server-latest.log.zip](https://github.com/zmaster587/AdvancedRocketry/files/1092758/fml-server-latest.log.zip)

**Comment by CovertJaguar** [comment]
No, it was an existing world that have Adv Rocketry added to it.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by moonheart08** [comment]
@dmodoomsirius I have encountered this issue once again, in the Omnifactory modpack on curseforge.
I am using Ubuntu 18.10.
