### ISSUE TITLE
Crashing with IndexOutOfBounds on asteroid mining mission completion

### ISSUE THREAD

**Issue by Forecaster** [zmaster587/AdvancedRocketry#747]
This crash: https://gist.github.com/Forecaster/8dc6a1bb638b44e38f4ad60f95f7351f

This asteroidConfig.xml: https://gist.github.com/Forecaster/09cd9630eee03676757f9b5c6981f902

The crash happened as soon as the asteroid mission completed, and now happens immediately on world load. The mission was to a "Radioactive" asteroid which also did not display the composition in the observatory.

I cannot find any errors from parsing the config in the log.

AdvancedRocketry-1.10.2-1.2.2
LibVulpes-1.10.2-0.2.5

**Comment by Forecaster** [comment]
The following asteroids from the config above does not display any content in the observatory and I'm not sure why. I can't tell if I've done something wrong with the entries and I don't know why the OutOfBounds error is happening.

```
Crystalized
Radioactive
Dusty
Endsteroid
```

They produce errors similar to this (non-crashing), but with different Index values, when clicking them in the list, and of course it stops it from updating the composition view:
```
[13:19:33] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 10, Size: 0
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.IndexOutOfBoundsException: Index: 10, Size: 0
	at java.util.LinkedList.checkElementIndex(Unknown Source) ~[?:1.8.0_131]
	at java.util.LinkedList.get(Unknown Source) ~[?:1.8.0_131]
	at zmaster587.advancedRocketry.util.AsteroidSmall.getHarvest(AsteroidSmall.java:85) ~[AsteroidSmall.class:?]
	at zmaster587.advancedRocketry.tile.multiblock.TileObservatory.getModules(TileObservatory.java:344) ~[TileObservatory.class:?]
	at zmaster587.libVulpes.inventory.GuiHandler.getServerGuiElement(GuiHandler.java:44) ~[GuiHandler.class:unspecified]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:251) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:87) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494) ~[zs.class:?]
	at zmaster587.advancedRocketry.tile.multiblock.TileObservatory.useNetworkData(TileObservatory.java:525) ~[TileObservatory.class:?]
	at zmaster587.libVulpes.network.PacketMachine.executeServer(PacketMachine.java:109) ~[PacketMachine.class:unspecified]
	at zmaster587.libVulpes.network.BasePacket$BasePacketHandlerServer$executor.run(BasePacket.java:120) ~[BasePacket$BasePacketHandlerServer$executor.class:unspecified]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
```

**Comment by zmaster587** [comment]
I'm wondering if you had invalid items or something in the config, would it be possible to send a log file, I know it might not be possible after all this time though.
