### ISSUE TITLE
World Crashing- Liquid Tank

### ISSUE THREAD

**Issue by GeebsRilie** [zmaster587/AdvancedRocketry#761]
Being in JEI and doing nothing else but going thru the pages I keep crashing with this message:

ItemStack crashed getting IBakedModel. 1xtile.pressurizedTank@0 advancedrocketry:liquidtank
java.lang.ClassCastException: net.minecraftforge.fluids.capability.templates.FluidHandlerItemStack cannot be cast to net.minecraftforge.common.model.animation.IAnimationStateMachine
	at net.minecraftforge.client.model.animation.AnimationItemOverrideList.handleItemState(AnimationItemOverrideList.java:70) ~[AnimationItemOverrideList.class:?]
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:248) ~[bvh.class:?]
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:269) ~[CCRenderItem.class:?]
	at mezz.jei.render.GuiIngredientFastList.set(GuiIngredientFastList.java:91) [GuiIngredientFastList.class:?]
	at mezz.jei.render.GuiIngredientFastList.set(GuiIngredientFastList.java:75) [GuiIngredientFastList.class:?]
	at mezz.jei.gui.overlay.IngredientGridAll.updateLayout(IngredientGridAll.java:28) [IngredientGridAll.class:?]
	at mezz.jei.gui.overlay.IngredientListOverlay.updateLayout(IngredientListOverlay.java:156) [IngredientListOverlay.class:?]
	at mezz.jei.gui.overlay.IngredientListOverlay.nextPage(IngredientListOverlay.java:190) [IngredientListOverlay.class:?]
	at mezz.jei.gui.PageNavigation.handleMouseClickedButtons(PageNavigation.java:68) [PageNavigation.class:?]
	at mezz.jei.gui.overlay.IngredientListOverlay.handleMouseClicked(IngredientListOverlay.java:250) [IngredientListOverlay.class:?]
	at mezz.jei.input.InputHandler.handleMouseClick(InputHandler.java:72) [InputHandler.class:?]
	at mezz.jei.input.InputHandler.handleMouseEvent(InputHandler.java:54) [InputHandler.class:?]
	at mezz.jei.gui.GuiEventHandler.onGuiMouseEvent(GuiEventHandler.java:137) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1065_GuiEventHandler_onGuiMouseEvent_Pre.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:511) [bho.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695) [bes.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by sandalle** [comment]
I think this might be related to the fluid issues of #721, #735, and https://github.com/zmaster587/AdvancedRocketry/issues/763 , can you try the fixed build from one of those?

**Comment by GeebsRilie** [comment]
Yes #721, it has to do with jei or something not being able to render the
animation of the liquid tank.

The foregoing may include confidential and/or privileged information.  If
you are not the intended recipient, do not read, distribute, reproduce or
otherwise disclose this transmission or any of its contents.  If delivered
in error, please forward the email back to sender, delete from your
computer and disregard information contained therein.  Thank you.

**Comment by zmaster587** [comment]
Should have been fixed a while back
