### ISSUE TITLE
NPE while click rolling machine

### ISSUE THREAD

**Issue by DPurple** [zmaster587/AdvancedRocketry#77]
sorry that i can't provide more information... because I can't replicate this problem and my bad english...
this problem happend only once... while i joined the server... try to open rolling machine's GUI...

here's exception information

java.lang.NullPointerException: Rendering Block Entity
	at zmaster587.advancedRocketry.client.render.multiblocks.RendererRollingMachine.func_147500_a(RendererRollingMachine.java:90)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

by some mysterious reason.. I can't upload files at github (ah....
I will try other way to provide the whole log file if you asked for....

**Comment by DPurple** [comment]
sorry that i can't provide more information... and my bad english...
this problem happend only once... while i joined the server... try open rolling machine...
it doesn't always happen... hopefully this helps....
