### ISSUE TITLE
Crash due to calling iterator.remove() on CopyOnWriteArrayList

### ISSUE THREAD

**Issue by oldjunyi** [zmaster587/AdvancedRocketry#785]
I have a server using AdvancedRocketry-1.10.2-1.0.19 (in Age of Engineering pack). After a user built some adv rocketry machines. The server keeps crash about 2~3 times a day. According to crash log:

> java.lang.UnsupportedOperationException
        at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176)
        at zmaster587.advancedRocketry.cable.CableNetwork.addSink(CableNetwork.java:74)
        at zmaster587.advancedRocketry.cable.HandlerCableNetwork.addSink(HandlerCableNetwork.java:111)
        at zmaster587.advancedRocketry.tile.cables.TilePipe.attemptLink(TilePipe.java:128)
        at zmaster587.advancedRocketry.tile.cables.TilePipe.linkSystems(TilePipe.java:104)
        at zmaster587.advancedRocketry.tile.cables.TilePipe.onPlaced(TilePipe.java:96)
        at zmaster587.advancedRocketry.block.cable.BlockPipe.func_189540_a(BlockPipe.java:83)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:463)
        at net.minecraft.world.World.func_180496_d(World.java:519)
        at net.minecraft.world.World.func_175685_c(World.java:468)

It seems the code is calling iterator.remove() on a CopyOnWriteArrayList, which does not support the iterator.remove() operation.
https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/cable/CableNetwork.java

**Comment by zmaster587** [comment]
should be fixed here:
http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/MC1_10/
