### ISSUE TITLE
[1.7.10] NullPointerException when connecting to server after playing in single player map

### ISSUE THREAD

**Issue by mskurnik** [zmaster587/AdvancedRocketry#816]
There is a fun little error that causes a player to be unable to join a server if they go into single player first.  This is similar to #760 but not occurring because of a server-side disconnect.

The game will show "A fatal error has occurred, this connection is terminated".  This seems to be a single player issue as no exception is thrown on the server.  If you try to connect multiple times, you hard crash and the game closes.

 - LibVulpes-1.7.10-0.2.5-universal
 - AdvancedRocketry-1.7.10-1.2.2

```
FMLIndexedMessageCodec exception caught
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at zmaster587.advancedRocketry.dimension.DimensionProperties.setStar(DimensionProperties.java:358)
	at zmaster587.advancedRocketry.dimension.DimensionProperties.readFromNBT(DimensionProperties.java:1186)
	at zmaster587.advancedRocketry.network.PacketDimInfo.readClient(PacketDimInfo.java:98)
	at zmaster587.libVulpes.network.PacketHandler$Codec.decodeInto(PacketHandler.java:115)
	at zmaster587.libVulpes.network.PacketHandler$Codec.decodeInto(PacketHandler.java:101)
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77)
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17)
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 18 more

There was a critical exception handling a packet on channel libVulpes
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at zmaster587.advancedRocketry.dimension.DimensionProperties.setStar(DimensionProperties.java:358)
	at zmaster587.advancedRocketry.dimension.DimensionProperties.readFromNBT(DimensionProperties.java:1186)
	at zmaster587.advancedRocketry.network.PacketDimInfo.readClient(PacketDimInfo.java:98)
	at zmaster587.libVulpes.network.PacketHandler$Codec.decodeInto(PacketHandler.java:115)
	at zmaster587.libVulpes.network.PacketHandler$Codec.decodeInto(PacketHandler.java:101)
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77)
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17)
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 18 more

```

**Comment by Sir-Will** [comment]
Same issue here.
@mskurnik do you know what data needs to be removed to fix the issue?

**Comment by mskurnik** [comment]
@Sir-Will No I do not.  My only thought is that an object is not being disposed of properly after closing a single player map.  If there is a way to turn on verbose logging with this mod I would be happy to provide more information.  If I can provide the message it is trying to decode I would think that would help the developer a bit.

**Comment by Sir-Will** [comment]
@zmaster587 would be great to get some input from you. I got like 5 players who can no longer join the server because of this issue and I have no idea where it stored the data which causes this issue.

**Comment by Sir-Will** [comment]
Made a rollback of `planetDefs.xml` and `temp.dat` on the server and deleted `advRocketry/temp.dat` on the client while it was open and it seems to have fixed it for all except one player.

**Comment by mskurnik** [comment]
Yeah but that is unrealistic for a player and sucks if you have changed the server planet defs.  What I tell people to do, is if they are leaving the server to play in single player to copy a building to schematica or using buildcraft architect table that when they do that to immediately load a new instance of the game and let that spool up in the background.  Once they are done in single player, they have to close the instance of Minecraft that they were playing in single player and then switch to the new instance.

It would be nice to see if @zmaster587 could tell us how to provide additional data.

**Comment by zmaster587** [comment]
I cannot see any mechanism that would allow data to persist through a full client restart, the /advRockety/temp.dat file has never been reported to be greater than 0 bytes in size and is not loaded client side.  (Called from FMLServerStartingEvent).  
If there was an issue with data reset I could see not being able to join a server until the client and closed an relaunched, there has been issues with that in the past.  But I don't know of any way it could persist past that.  I'll try to replicate it so see what I can dig up.  But it looks like it's trying to assign a moon to a nonexistant planet.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
