### ISSUE TITLE
ConcurrentModificationException with cables

### ISSUE THREAD

**Issue by Sir-Will** [zmaster587/AdvancedRocketry#850]
Opened new issue as the other issue are closed. (https://github.com/zmaster587/AdvancedRocketry/issues/545, https://github.com/zmaster587/AdvancedRocketry/issues/475)

AdvancedRocketry-1.10.2-1.2.2
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
	at zmaster587.advancedRocketry.cable.HandlerDataNetwork.tickAllNetworks(HandlerDataNetwork.java:20)
	at zmaster587.advancedRocketry.event.CableTickHandler.onTick(CableTickHandler.java:26)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_685_CableTickHandler_onTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:588)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
	at zmaster587.advancedRocketry.cable.HandlerDataNetwork.tickAllNetworks(HandlerDataNetwork.java:20)
	at zmaster587.advancedRocketry.event.CableTickHandler.onTick(CableTickHandler.java:26)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_685_CableTickHandler_onTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632)

-- Sponge CauseTracker --
Details:
	Cause Stack: /********************************************************************************************************/
/*   - Phase: org.spongepowered.common.event.tracking.phase.plugin.PostServerTickListenerState@591e6992 */
/*     Context:                                                                                         */
/*     - Name: Source                                                                                   */
/*       Object: ASM: zmaster587.advancedRocketry.event.CableTickHandler@35747b53                       */
/*       onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V                   */
/*     - Name: CapturedWorldTickEvent                                                                   */
/*       Object: net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@46a0783              */
/*     - Name: CapturedBlocks                                                                           */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                     */
/*     - Name: CapturedEntities                                                                         */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                   */
/*     - Name: CapturedPlayer                                                                           */
/*       Object: CapturePlayer{player=null}                                                             */
/********************************************************************************************************/

Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zhp000(MinecraftServer.java:3956)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:361)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:503)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zmaster587** [comment]
HashMap is not thread safe, switched to hashtable.  I still can't see any reason there'd be multiple threads running at once short of speciallized optimization mods, but anyway... the change should fix it.

**Comment by Sir-Will** [comment]
I changed it myself to `ConcurrentHashMap` and since then I had no crash once.

**Comment by zmaster587** [comment]
Alright, good to hear, the next release should contain the patch too.  Also in the future, if you do make patches like that, a PR would be greatly appriciated.  I have very little time to work on AR nowadays so even small things help a lot.  Cheers!
