### ISSUE TITLE
Crash when unmanned vehicle return to base

### ISSUE THREAD

**Issue by JoKangHyeon** [zmaster587/AdvancedRocketry#883]
MC 1.11.2
AdvancedRocketry-1.11.2-1.2.4
LibVulpes-1.11.2-0.2.6

The game crashed when my unmanned vehicle returned to base.

java.util.ConcurrentModificationException
 at java.util.HashMap$HashIterator.nextNode(Unknown Source)
 at java.util.HashMap$ValueIterator.next(Unknown Source)
 at zmaster587.advancedRocketry.dimension.DimensionProperties.tick(DimensionProperties.java:791)
 at zmaster587.advancedRocketry.dimension.DimensionManager.tickDimensions(DimensionManager.java:189)
 at zmaster587.advancedRocketry.event.PlanetEventHandler.tick(PlanetEventHandler.java:228)
 at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_906_PlanetEventHandler_tick_ServerTickEvent.invoke(.dynamic)
 at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
 at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
 at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
 at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
 at java.lang.Thread.run(Unknown Source)

**Comment by dmodoomsirius** [comment]
Does this still occur?
