### ISSUE TITLE
[1.12.2] Error on joining server

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#941]
Minecraft Version:
- 1.12.2
Forge Version:
- 2517
Advanced Rocketry Version:
- 1.2.5a-15
LibVulpes Version:
- 0.2.6-8

Explain issue in detail:
Suddenly cannot join a multiplayer server due to the following error:
```
Caused by: java.lang.NullPointerException
	at zmaster587.advancedRocketry.dimension.DimensionProperties.setStar(DimensionProperties.java:342) ~[DimensionProperties.class:?]
	at zmaster587.advancedRocketry.dimension.DimensionProperties.readFromNBT(DimensionProperties.java:1190) ~[DimensionProperties.class:?]
	at zmaster587.advancedRocketry.network.PacketDimInfo.readClient(PacketDimInfo.java:104) ~[PacketDimInfo.class:?]
	at zmaster587.libVulpes.network.PacketHandler$Codec.decodeInto(PacketHandler.java:210) ~[PacketHandler$Codec.class:?]
	at zmaster587.libVulpes.network.PacketHandler$Codec.decodeInto(PacketHandler.java:192) ~[PacketHandler$Codec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:103) ~[FMLIndexedMessageToMessageCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:40) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[MessageToMessageDecoder.class:4.1.9.Final]
	... 59 more
```

this happens continually for one player, but not for the other 3 on the server.  That player did a complete re-install of all mods, and the issue persisted.  An attempt was made to delete the data for the player as well, and the problem still persisted.

**Comment by Thutmose** [comment]
Deleting all of the planet dimensions, as well as the planetDefs.xml seems to have fixed the issue, the planetDefs.xml had somehow turned to:

```XML
<galaxy>
</galaxy>
```

**Comment by zmaster587** [comment]
Deleting the dimensions on the server?  Also is that trace from the server or client?

**Comment by Thutmose** [comment]
hmm, it didn't repopulate the xml, though deleting it did fix the one client not being able to rejoin.  The server was restarted several times during the same time period, and the other two players could still log on, the only issue noticed for other players as an instance of #937 for when a player got near a rocket that had been sitting around for a while, that rocket had about 200k infrastructure locations saved.  The player who wasn't near any rockets didn't notice any issues at all.

The player who was having the issues was located at that rocket, however even deleting their player data didn't fix anything, so it shouldn't have been related to the rocket, the error seemed to be entirely on the side of that client.

This was tested with the player who couldn't join having opened single player, not opening single player, re-installing minecraft, then trying both of those cases again.

**Comment by zmaster587** [comment]
#937 should be fixed now.  If the players who can join restart their client are they still able to join?
What I think is happening is that the actual storage for the stars on the server is being erased or lost.  Thats the only way I'm aware of that would cause both the save to break and serialization of data.

**Comment by Thutmose** [comment]
I haven't noticed this issue occur lately, so I am not sure what happened to it, the other players could rejoin after restarting their clients, the only error that was noticed was the case of #937 for one who logged off too close to an affected rocket
