### ISSUE TITLE
Using a Space Station Segment with an Space Elevator on Top causes crash

### ISSUE THREAD

**Issue by dredhorse** [zmaster587/AdvancedRocketry#977]
Minecraft Version: 1.10.2
-
Forge Version: 12.18.3.2511 
-
Advanced Rocketry Version: 1.2.2
-
LibVulpes Version: 0.2.5
-
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:

I created a space station segment with a space elevator on top. This autofinishes itself for whatever. I scaned and build the space station segment nevertheless and added the satelite bay to the rocket.

As soon as the other world with the space stations load I get this crash, is guess it isn't a good idea to pack a multblock item.

Any idea on how I can save my world?

Time: 12/5/17 7:59 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at zmaster587.libVulpes.tile.multiblock.TileMultiBlock.completeStructure(TileMultiBlock.java:334)
	at zmaster587.libVulpes.tile.multiblock.TileMultiPowerConsumer.func_73660_a(TileMultiPowerConsumer.java:141)
	at zmaster587.advancedRocketry.tile.multiblock.TileSpaceElevator.func_73660_a(TileSpaceElevator.java:257)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at zmaster587.libVulpes.tile.multiblock.TileMultiBlock.completeStructure(TileMultiBlock.java:334)
	at zmaster587.libVulpes.tile.multiblock.TileMultiPowerConsumer.func_73660_a(TileMultiPowerConsumer.java:141)
	at zmaster587.advancedRocketry.tile.multiblock.TileSpaceElevator.func_73660_a(TileSpaceElevator.java:257)

-- Block entity being ticked --
Details:
	Name: ARSpaceElevator // zmaster587.advancedRocketry.tile.multiblock.TileSpaceElevator
	Block type: ID #2746 (tile.spaceElevatorController // zmaster587.libVulpes.block.multiblock.BlockMultiblockMachine)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-1524,129,-1520), Chunk: (at 12,8,0 in -96,-95; contains blocks -1536,0,-1520 to -1521,255,-1505), Region: (-3,-3; contains chunks -96,-96 to -65,-65, blocks -1536,0,-1536 to -1025,255,-1025)
	Actual block type: ID #2746 (tile.spaceElevatorController // zmaster587.libVulpes.block.multiblock.BlockMultiblockMachine)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

**Comment by dmodoomsirius** [comment]
please use something similar to [http://pastebin.com](http://pastebin.com ) next time and link the whole crash report.

**Comment by zmaster587** [comment]
Im not 100% sure how this could occur, would it be at all possible to send the region file?

**Comment by dredhorse** [comment]
Hi, I can only give you the steps to recreate it as I have already progressed beyond that.

Build Space Station Platform with assembled Space Station Elevator.
Put Space Station into Rocket, jump on Rocket.
Start with Rocket
Switch to Orbit and crash

I got rid of the crash by hacking the Block out of the save. Afterwards, I removed all the "fake" blocks and recreated the elevator

Finalizing the Elevator again caused a crash again.

Attached the crash logs, you can also see some stuff on my youtube if you like (German language though)

[Crashes.zip](https://github.com/zmaster587/AdvancedRocketry/files/1562471/Crashes.zip)

**Comment by zmaster587** [comment]
I think what's happening is that the multiblocks when sent up into space in a space station container are not properly being updated with their new position.  I've confirmed this issue occurs not only with the Space Elevator, but any multiblock structure from AR.  If you build a new space elevator on the spacestation already in orbit, I would expect it to work properly.  Can you test that?

**Comment by dredhorse** [comment]
I already did that... it doesn't work.. https://youtu.be/w1LPK9jYbFI?t=27m14s

**Comment by zmaster587** [comment]
The redstone lamps can't be lit
