### ISSUE TITLE
[1.12.2] Biome changer is broken

### ISSUE THREAD

**Issue by polyzium** [zmaster587/AdvancedRocketry#985]
Minecraft Version:
1.12.2
Forge Version:
14.23.1.2560
Advanced Rocketry Version:
1.2.6-5
LibVulpes Version:
0.2.7-19-universal
**is this the latest curseforge build?**
Yes
#Please Pastebin crash
no crash
Crash Report:
no crash
Explain issue in detail:
Playing on a server that i host. Each time i right click the biome changer, i don't get it's GUI and this gets printed into the server's console:
```
[23:20:31] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.0.0-BETA-2758]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zih000(MinecraftServer.java:4008) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at zmaster587.advancedRocketry.tile.multiblock.TileBiomeScanner.getModules(TileBiomeScanner.java:95) ~[TileBiomeScanner.class:?]
	at zmaster587.libVulpes.inventory.GuiHandler.getServerGuiElement(GuiHandler.java:44) ~[GuiHandler.class:unspecified]
	at net.minecraftforge.fml.common.network.NetworkRegistry.redirect$setRemoteContainerPlugin$zpi000(NetworkRegistry.java:547) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:254) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:87) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at zmaster587.libVulpes.block.multiblock.BlockMultiblockMachine.func_180639_a(BlockMultiblockMachine.java:86) ~[BlockMultiblockMachine.class:unspecified]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1246) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zhm000(NetHandlerPlayServer.java:2376) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) ~[PacketUtil.class:1.12.2-2555-7.0.0-BETA-2758]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkf000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
```

**Comment by zmaster587** [comment]
should be fixed in the next build
